// 拼音字母数据

export interface PinyinLetter {
  letter: string;
  pinyin: string;
  category: 'shengmu' | 'yunmu' | 'zhengtiren';
  examples: string[];
  emoji: string;
}

// 声母
export const shengmu: PinyinLetter[] = [
  { letter: 'b', pinyin: 'bō', category: 'shengmu', examples: ['爸爸', '宝宝', '抱抱'], emoji: '👶' },
  { letter: 'p', pinyin: 'pō', category: 'shengmu', examples: ['爬', '跑', '拍'], emoji: '🏃' },
  { letter: 'm', pinyin: 'mō', category: 'shengmu', examples: ['妈妈', '猫', '摸'], emoji: '😺' },
  { letter: 'f', pinyin: 'fó', category: 'shengmu', examples: ['饭', '飞', '风'], emoji: '🍚' },
  { letter: 'd', pinyin: 'dé', category: 'shengmu', examples: ['大', '弟弟', '跳舞'], emoji: '💃' },
  { letter: 't', pinyin: 'tè', category: 'shengmu', examples: ['他', '太', '跳'], emoji: '🦘' },
  { letter: 'n', pinyin: 'nè', category: 'shengmu', examples: ['你', '鸟', '牛奶'], emoji: '🐦' },
  { letter: 'l', pinyin: 'lè', category: 'shengmu', examples: ['来', '拉', '乐'], emoji: '😊' },
  { letter: 'g', pinyin: 'gē', category: 'shengmu', examples: ['狗', '哥哥', '瓜'], emoji: '🐕' },
  { letter: 'k', pinyin: 'kē', category: 'shengmu', examples: ['看', '哭', '开心'], emoji: '👀' },
  { letter: 'h', pinyin: 'hē', category: 'shengmu', examples: ['喝', '花', '好'], emoji: '🌸' },
  { letter: 'j', pinyin: 'jī', category: 'shengmu', examples: ['鸡', '家', '姐姐'], emoji: '🐔' },
  { letter: 'q', pinyin: 'qī', category: 'shengmu', examples: ['七', '去', '气球'], emoji: '🎈' },
  { letter: 'x', pinyin: 'xī', category: 'shengmu', examples: ['西瓜', '笑', '星星'], emoji: '🍉' },
  { letter: 'zh', pinyin: 'zhī', category: 'shengmu', examples: ['蜘蛛', '猪', '纸'], emoji: '🐷' },
  { letter: 'ch', pinyin: 'chī', category: 'shengmu', examples: ['吃', '虫', '车'], emoji: '🍴' },
  { letter: 'sh', pinyin: 'shī', category: 'shengmu', examples: ['书', '手', '水'], emoji: '📚' },
  { letter: 'r', pinyin: 'rì', category: 'shengmu', examples: ['日', '热', '肉'], emoji: '☀️' },
  { letter: 'z', pinyin: 'zī', category: 'shengmu', examples: ['字', '走', '嘴'], emoji: '👄' },
  { letter: 'c', pinyin: 'cī', category: 'shengmu', examples: ['草', '菜', '擦'], emoji: '🌱' },
  { letter: 's', pinyin: 'sī', category: 'shengmu', examples: ['三', '色', '山'], emoji: '⛰️' },
  { letter: 'y', pinyin: 'yī', category: 'shengmu', examples: ['一', '鱼', '月'], emoji: '🐟' },
  { letter: 'w', pinyin: 'wū', category: 'shengmu', examples: ['五', '我', '蛙'], emoji: '🐸' },
];

// 韵母 - 单韵母
export const dunyunmu: PinyinLetter[] = [
  { letter: 'a', pinyin: 'ā', category: 'yunmu', examples: ['阿姨', '鸭', '大'], emoji: '🦆' },
  { letter: 'o', pinyin: 'ō', category: 'yunmu', examples: ['哦', '婆', '波'], emoji: '🌊' },
  { letter: 'e', pinyin: 'ē', category: 'yunmu', examples: ['鹅', '额', '饿'], emoji: '🦢' },
  { letter: 'i', pinyin: 'ī', category: 'yunmu', examples: ['衣', '椅', '一'], emoji: '👕' },
  { letter: 'u', pinyin: 'ū', category: 'yunmu', examples: ['乌', '屋', '五'], emoji: '🏠' },
  { letter: 'ü', pinyin: 'ǖ', category: 'yunmu', examples: ['鱼', '雨', '羽'], emoji: '🌧️' },
];

// 韵母 - 复韵母
export const fuyunmu: PinyinLetter[] = [
  { letter: 'ai', pinyin: 'āi', category: 'yunmu', examples: ['爱', '奶奶', '开'], emoji: '❤️' },
  { letter: 'ei', pinyin: 'ēi', category: 'yunmu', examples: ['飞', '妹', '黑'], emoji: '✈️' },
  { letter: 'ui', pinyin: 'uī', category: 'yunmu', examples: ['水', '腿', '队'], emoji: '💧' },
  { letter: 'ao', pinyin: 'āo', category: 'yunmu', examples: ['袄', '宝宝', '草'], emoji: '🍚' },
  { letter: 'ou', pinyin: 'ōu', category: 'yunmu', examples: ['手', '狗', '走'], emoji: '🐾' },
  { letter: 'iu', pinyin: 'iū', category: 'yunmu', examples: ['牛', '球', '流'], emoji: '🎾' },
  { letter: 'ie', pinyin: 'iē', category: 'yunmu', examples: ['姐', '爷', '叶'], emoji: '🍂' },
  { letter: 'üe', pinyin: 'üē', category: 'yunmu', examples: ['月', '雪', '学'], emoji: '❄️' },
  { letter: 'er', pinyin: 'ēr', category: 'yunmu', examples: ['耳', '二', '儿'], emoji: '👂' },
  { letter: 'an', pinyin: 'ān', category: 'yunmu', examples: ['安', '饭', '班'], emoji: '🍛' },
  { letter: 'en', pinyin: 'ēn', category: 'yunmu', examples: ['恩', '门', '人'], emoji: '🚪' },
  { letter: 'in', pinyin: 'īn', category: 'yunmu', examples: ['音', '金', '心'], emoji: '💛' },
  { letter: 'un', pinyin: 'ūn', category: 'yunmu', examples: ['温', '论', '棍'], emoji: '🌡️' },
  { letter: 'ün', pinyin: 'ǖn', category: 'yunmu', examples: ['云', '匀', '军'], emoji: '☁️' },
  { letter: 'ang', pinyin: 'āng', category: 'yunmu', examples: ['昂', '方', '羊'], emoji: '🐑' },
  { letter: 'eng', pinyin: 'ēng', category: 'yunmu', examples: ['灯', '风', '梦'], emoji: '💡' },
  { letter: 'ing', pinyin: 'īng', category: 'yunmu', examples: ['鹰', '星', '听'], emoji: '🦅' },
  { letter: 'ong', pinyin: 'ōng', category: 'yunmu', examples: ['龙', '红', '中'], emoji: '🐲' },
];

// 整体认读音节
export const zhengtiren: PinyinLetter[] = [
  { letter: 'zhi', pinyin: 'zhī', category: 'zhengtiren', examples: ['纸', '只', '指'], emoji: '📄' },
  { letter: 'chi', pinyin: 'chī', category: 'zhengtiren', examples: ['吃', '池', '尺'], emoji: '🍽️' },
  { letter: 'shi', pinyin: 'shī', category: 'zhengtiren', examples: ['师', '诗', '十'], emoji: '📖' },
  { letter: 'ri', pinyin: 'rì', category: 'zhengtiren', examples: ['日', '入', '热'], emoji: '🌞' },
  { letter: 'zi', pinyin: 'zī', category: 'zhengtiren', examples: ['子', '字', '紫'], emoji: '💜' },
  { letter: 'ci', pinyin: 'cī', category: 'zhengtiren', examples: ['次', '词', '刺'], emoji: '🎯' },
  { letter: 'si', pinyin: 'sī', category: 'zhengtiren', examples: ['思', '四', '丝'], emoji: '🎀' },
  { letter: 'yi', pinyin: 'yī', category: 'zhengtiren', examples: ['一', '衣', '医'], emoji: '👔' },
  { letter: 'wu', pinyin: 'wū', category: 'zhengtiren', examples: ['五', '无', '屋'], emoji: '🏡' },
  { letter: 'yu', pinyin: 'yū', category: 'zhengtiren', examples: ['鱼', '雨', '玉'], emoji: '💎' },
  { letter: 'ye', pinyin: 'yē', category: 'zhengtiren', examples: ['爷', '夜', '叶'], emoji: '🌙' },
  { letter: 'yue', pinyin: 'yuē', category: 'zhengtiren', examples: ['月', '乐', '越'], emoji: '🌕' },
  { letter: 'yuan', pinyin: 'yuān', category: 'zhengtiren', examples: ['圆', '原', '园'], emoji: '⭕' },
  { letter: 'yin', pinyin: 'yīn', category: 'zhengtiren', examples: ['音', '银', '因'], emoji: '🎵' },
  { letter: 'yun', pinyin: 'yūn', category: 'zhengtiren', examples: ['云', '匀', '允'], emoji: '🌤️' },
  { letter: 'ying', pinyin: 'yīng', category: 'zhengtiren', examples: ['鹰', '赢', '英'], emoji: '🏆' },
];

export const categoryNames = {
  shengmu: '声母',
  yunmu: '韵母',
  zhengtiren: '整体认读音节',
};

export const subCategoryNames = {
  dunyunmu: '单韵母',
  fuyunmu: '复韵母',
};

// 汉字学习数据
export interface HanziCharacter {
  character: string;
  pinyin: string;
  strokes: number;
  words: string[];
  category: string;
  emoji: string;
  level: 'basic' | 'intermediate' | 'advanced'; // 难度级别
}

// 常用汉字分类
export const hanziCategories = [
  { id: 'family', name: '家庭人物', emoji: '👨‍👩‍👧' },
  { id: 'nature', name: '自然事物', emoji: '🌳' },
  { id: 'animals', name: '动物世界', emoji: '🐾' },
  { id: 'body', name: '身体部位', emoji: '🖐️' },
  { id: 'food', name: '食物水果', emoji: '🍎' },
  { id: 'colors', name: '颜色形状', emoji: '🎨' },
  { id: 'numbers', name: '数字时间', emoji: '🔢' },
  { id: 'daily', name: '日常生活', emoji: '🏠' },
  { id: 'school', name: '学习用品', emoji: '📚' },
  { id: 'clothes', name: '服装衣物', emoji: '👕' },
  { id: 'vehicles', name: '交通工具', emoji: '🚗' },
  { id: 'places', name: '场所地点', emoji: '🏢' },
];

// 汉字数据
export const hanziData: Record<string, HanziCharacter[]> = {
  family: [
    { character: '爸', pinyin: 'bà', strokes: 8, words: ['爸爸', '老爸', '阿爸'], category: 'family', emoji: '👨', level: 'basic' },
    { character: '妈', pinyin: 'mā', strokes: 6, words: ['妈妈', '老妈', '姑妈'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '宝', pinyin: 'bǎo', strokes: 8, words: ['宝宝', '宝贝', '珍宝'], category: 'family', emoji: '👶' , level: 'basic' },
    { character: '哥', pinyin: 'gē', strokes: 10, words: ['哥哥', '大哥', '哥哥们'], category: 'family', emoji: '🧑' , level: 'basic' },
    { character: '姐', pinyin: 'jiě', strokes: 8, words: ['姐姐', '大姐', '姐妹'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '弟', pinyin: 'dì', strokes: 7, words: ['弟弟', '小弟', '兄弟'], category: 'family', emoji: '🧒' , level: 'basic' },
    { character: '妹', pinyin: 'mèi', strokes: 8, words: ['妹妹', '小妹', '姐妹'], category: 'family', emoji: '👧' , level: 'basic' },
    { character: '奶', pinyin: 'nǎi', strokes: 5, words: ['奶奶', '牛奶', '奶粉'], category: 'family', emoji: '👵' , level: 'basic' },
    { character: '爷', pinyin: 'yé', strokes: 6, words: ['爷爷', '大爷', '老爷'], category: 'family', emoji: '👴' , level: 'basic' },
    { character: '父', pinyin: 'fù', strokes: 4, words: ['父亲', '父母', '父子'], category: 'family', emoji: '👨' , level: 'basic' },
    { character: '母', pinyin: 'mǔ', strokes: 5, words: ['母亲', '父母', '母爱'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '亲', pinyin: 'qīn', strokes: 9, words: ['亲人', '母亲', '亲爱'], category: 'family', emoji: '👨‍👩‍👧' , level: 'basic' },
    { character: '家', pinyin: 'jiā', strokes: 10, words: ['家庭', '大家', '家人'], category: 'family', emoji: '🏠' , level: 'basic' },
    { character: '舅', pinyin: 'jiù', strokes: 13, words: ['舅舅', '大舅', '小舅'], category: 'family', emoji: '🧑' , level: 'intermediate' },
    { character: '姨', pinyin: 'yí', strokes: 9, words: ['阿姨', '大姨', '姨妈'], category: 'family', emoji: '👩' , level: 'intermediate' },
    { character: '姑', pinyin: 'gū', strokes: 8, words: ['姑姑', '小姑', '姑妈'], category: 'family', emoji: '👩' , level: 'intermediate' },
    { character: '伯', pinyin: 'bó', strokes: 7, words: ['伯父', '大伯', '伯父'], category: 'family', emoji: '👨' , level: 'intermediate' },
    { character: '孙', pinyin: 'sūn', strokes: 6, words: ['孙子', '孙女', '外孙'], category: 'family', emoji: '👶' , level: 'intermediate' },
    { character: '童', pinyin: 'tóng', strokes: 12, words: ['儿童', '童年', '童趣'], category: 'family', emoji: '👶' , level: 'intermediate' },
  ],
  nature: [
    { character: '日', pinyin: 'rì', strokes: 4, words: ['日子', '日月', '生日'], category: 'nature', emoji: '☀️' , level: 'basic' },
    { character: '月', pinyin: 'yuè', strokes: 4, words: ['月亮', '日月', '月牙'], category: 'nature', emoji: '🌙' , level: 'basic' },
    { character: '水', pinyin: 'shuǐ', strokes: 4, words: ['水果', '水杯', '喝水'], category: 'nature', emoji: '💧' , level: 'basic' },
    { character: '火', pinyin: 'huǒ', strokes: 4, words: ['火柴', '火车', '火红'], category: 'nature', emoji: '🔥' , level: 'basic' },
    { character: '山', pinyin: 'shān', strokes: 3, words: ['大山', '高山', '山脉'], category: 'nature', emoji: '⛰️' , level: 'basic' },
    { character: '风', pinyin: 'fēng', strokes: 4, words: ['大风', '风光', '风景'], category: 'nature', emoji: '🌬️' , level: 'basic' },
    { character: '雨', pinyin: 'yǔ', strokes: 8, words: ['下雨', '大雨', '小雨'], category: 'nature', emoji: '🌧️' , level: 'basic' },
    { character: '雪', pinyin: 'xuě', strokes: 11, words: ['雪花', '白雪', '下雪'], category: 'nature', emoji: '❄️' , level: 'basic' },
    { character: '云', pinyin: 'yún', strokes: 4, words: ['白云', '云朵', '乌云'], category: 'nature', emoji: '☁️' , level: 'basic' },
    { character: '花', pinyin: 'huā', strokes: 7, words: ['花朵', '花园', '花朵'], category: 'nature', emoji: '🌸' , level: 'basic' },
    { character: '树', pinyin: 'shù', strokes: 9, words: ['树木', '大树', '树林'], category: 'nature', emoji: '🌳' , level: 'basic' },
    { character: '草', pinyin: 'cǎo', strokes: 9, words: ['小草', '青草', '草地'], category: 'nature', emoji: '🌱' , level: 'basic' },
    { character: '石', pinyin: 'shí', strokes: 5, words: ['石头', '岩石', '玉石'], category: 'nature', emoji: '🪨' , level: 'basic' },
    { character: '田', pinyin: 'tián', strokes: 5, words: ['田地', '田野', '水田'], category: 'nature', emoji: '🌾' , level: 'basic' },
    { character: '冰', pinyin: 'bīng', strokes: 6, words: ['冰块', '冰雪', '冰冻'], category: 'nature', emoji: '🧊' , level: 'intermediate' },
    { character: '海', pinyin: 'hǎi', strokes: 10, words: ['大海', '海洋', '海边'], category: 'nature', emoji: '🌊' , level: 'intermediate' },
    { character: '河', pinyin: 'hé', strokes: 8, words: ['河水', '小河', '河流'], category: 'nature', emoji: '🌊' , level: 'intermediate' },
    { character: '湖', pinyin: 'hú', strokes: 12, words: ['湖水', '湖泊', '江湖'], category: 'nature', emoji: '🏞️' , level: 'intermediate' },
    { character: '雷', pinyin: 'léi', strokes: 13, words: ['雷电', '雷雨', '打雷'], category: 'nature', emoji: '⚡' , level: 'intermediate' },
    { character: '电', pinyin: 'diàn', strokes: 5, words: ['闪电', '电力', '电子'], category: 'nature', emoji: '⚡' , level: 'intermediate' },
  ],
  animals: [
    { character: '鸟', pinyin: 'niǎo', strokes: 5, words: ['小鸟', '飞鸟', '鸟儿'], category: 'animals', emoji: '🐦' , level: 'basic' },
    { character: '鸡', pinyin: 'jī', strokes: 7, words: ['小鸡', '公鸡', '鸡蛋'], category: 'animals', emoji: '🐔' , level: 'basic' },
    { character: '猪', pinyin: 'zhū', strokes: 11, words: ['小猪', '肥猪', '猪圈'], category: 'animals', emoji: '🐷' , level: 'basic' },
    { character: '狗', pinyin: 'gǒu', strokes: 8, words: ['小狗', '黄狗', '狗窝'], category: 'animals', emoji: '🐕' , level: 'basic' },
    { character: '猫', pinyin: 'māo', strokes: 11, words: ['小猫', '白猫', '猫咪'], category: 'animals', emoji: '🐱' , level: 'basic' },
    { character: '鱼', pinyin: 'yú', strokes: 8, words: ['小鱼', '金鱼', '鱼儿'], category: 'animals', emoji: '🐟' , level: 'basic' },
    { character: '牛', pinyin: 'niú', strokes: 4, words: ['小牛', '黄牛', '牛儿'], category: 'animals', emoji: '🐄' , level: 'basic' },
    { character: '马', pinyin: 'mǎ', strokes: 10, words: ['小马', '白马', '马儿'], category: 'animals', emoji: '🐴' , level: 'basic' },
    { character: '羊', pinyin: 'yáng', strokes: 6, words: ['小羊', '白羊', '羊儿'], category: 'animals', emoji: '🐑' , level: 'basic' },
    { character: '兔', pinyin: 'tù', strokes: 8, words: ['兔子', '小兔', '白兔'], category: 'animals', emoji: '🐰' , level: 'basic' },
    { character: '虎', pinyin: 'hǔ', strokes: 8, words: ['老虎', '虎头', '小虎'], category: 'animals', emoji: '🐯' , level: 'basic' },
    { character: '狮', pinyin: 'shī', strokes: 9, words: ['狮子', '雄狮', '狮王'], category: 'animals', emoji: '🦁' , level: 'basic' },
    { character: '象', pinyin: 'xiàng', strokes: 11, words: ['大象', '白象', '象牙'], category: 'animals', emoji: '🐘' , level: 'basic' },
    { character: '猴', pinyin: 'hóu', strokes: 12, words: ['猴子', '小猴', '猴王'], category: 'animals', emoji: '🐵' , level: 'basic' },
    { character: '鹿', pinyin: 'lù', strokes: 11, words: ['鹿', '梅花鹿', '小鹿'], category: 'animals', emoji: '🦌' , level: 'intermediate' },
    { character: '熊', pinyin: 'xióng', strokes: 14, words: ['熊', '熊猫', '狗熊'], category: 'animals', emoji: '🐻' , level: 'intermediate' },
    { character: '狼', pinyin: 'láng', strokes: 10, words: ['狼', '狼群', '大灰狼'], category: 'animals', emoji: '🐺' , level: 'advanced' },
    { character: '虫', pinyin: 'chóng', strokes: 6, words: ['虫子', '昆虫', '害虫'], category: 'animals', emoji: '🐛' , level: 'intermediate' },
    { character: '龙', pinyin: 'lóng', strokes: 5, words: ['龙', '龙凤', '龙灯'], category: 'animals', emoji: '🐉' , level: 'advanced' },
  ],
  body: [
    { character: '手', pinyin: 'shǒu', strokes: 4, words: ['大手', '小手', '双手'], category: 'body', emoji: '🖐️' , level: 'basic' },
    { character: '口', pinyin: 'kǒu', strokes: 3, words: ['大口', '小口', '口水'], category: 'body', emoji: '👄' , level: 'basic' },
    { character: '耳', pinyin: 'ěr', strokes: 6, words: ['耳朵', '左耳', '右耳'], category: 'body', emoji: '👂' , level: 'basic' },
    { character: '目', pinyin: 'mù', strokes: 5, words: ['目光', '目标', '目的'], category: 'body', emoji: '👁️' , level: 'basic' },
    { character: '足', pinyin: 'zú', strokes: 7, words: ['足球', '十足', '手足'], category: 'body', emoji: '🦶' , level: 'basic' },
    { character: '心', pinyin: 'xīn', strokes: 4, words: ['开心', '心情', '爱心'], category: 'body', emoji: '❤️' , level: 'basic' },
    { character: '头', pinyin: 'tóu', strokes: 5, words: ['回头', '开头', '头发'], category: 'body', emoji: '🗣️' , level: 'basic' },
    { character: '牙', pinyin: 'yá', strokes: 4, words: ['牙齿', '门牙', '刷牙'], category: 'body', emoji: '🦷' , level: 'basic' },
    { character: '脸', pinyin: 'liǎn', strokes: 9, words: ['脸', '笑脸', '脸蛋'], category: 'body', emoji: '😊' , level: 'basic' },
    { character: '舌', pinyin: 'shé', strokes: 6, words: ['舌头', '长舌', '香舌'], category: 'body', emoji: '👅' , level: 'basic' },
    { character: '鼻', pinyin: 'bí', strokes: 14, words: ['鼻子', '鼻孔', '鼻头'], category: 'body', emoji: '👃' , level: 'basic' },
    { character: '眼', pinyin: 'yǎn', strokes: 11, words: ['眼睛', '眼镜', '眼泪'], category: 'body', emoji: '👁️' , level: 'basic' },
    { character: '毛', pinyin: 'máo', strokes: 4, words: ['羽毛', '毛发', '眉毛'], category: 'body', emoji: '💇' , level: 'intermediate' },
    { character: '血', pinyin: 'xuè', strokes: 6, words: ['血液', '血管', '流血'], category: 'body', emoji: '🩸' , level: 'intermediate' },
    { character: '骨', pinyin: 'gǔ', strokes: 10, words: ['骨头', '骨头', '骨骼'], category: 'body', emoji: '🦴' , level: 'intermediate' },
    { character: '皮', pinyin: 'pí', strokes: 5, words: ['皮肤', '牛皮', '果皮'], category: 'body', emoji: '🧴' , level: 'intermediate' },
    { character: '肉', pinyin: 'ròu', strokes: 6, words: ['肌肉', '骨肉', '肥肉'], category: 'body', emoji: '💪' , level: 'intermediate' },
  ],
  food: [
    { character: '饭', pinyin: 'fàn', strokes: 7, words: ['米饭', '吃饭', '晚饭'], category: 'food', emoji: '🍚' , level: 'basic' },
    { character: '肉', pinyin: 'ròu', strokes: 6, words: ['猪肉', '牛肉', '羊肉'], category: 'food', emoji: '🥩' , level: 'basic' },
    { character: '菜', pinyin: 'cài', strokes: 11, words: ['蔬菜', '青菜', '白菜'], category: 'food', emoji: '🥬' , level: 'basic' },
    { character: '蛋', pinyin: 'dàn', strokes: 11, words: ['鸡蛋', '鸭蛋', '蛋糕'], category: 'food', emoji: '🥚' , level: 'basic' },
    { character: '果', pinyin: 'guǒ', strokes: 8, words: ['水果', '苹果', '结果'], category: 'food', emoji: '🍎' , level: 'basic' },
    { character: '瓜', pinyin: 'guā', strokes: 5, words: ['西瓜', '南瓜', '甜瓜'], category: 'food', emoji: '🍉' , level: 'basic' },
    { character: '米', pinyin: 'mǐ', strokes: 6, words: ['大米', '小米', '米饭'], category: 'food', emoji: '🍚' , level: 'basic' },
    { character: '面', pinyin: 'miàn', strokes: 9, words: ['面条', '方便面', '面粉'], category: 'food', emoji: '🍜' , level: 'basic' },
    { character: '甜', pinyin: 'tián', strokes: 11, words: ['甜美', '甜味', '香甜'], category: 'food', emoji: '🍬' , level: 'basic' },
    { character: '酸', pinyin: 'suān', strokes: 12, words: ['酸甜', '酸味', '酸酸'], category: 'food', emoji: '🍋' , level: 'basic' },
    { character: '苦', pinyin: 'kǔ', strokes: 8, words: ['辛苦', '苦瓜', '苦味'], category: 'food', emoji: '🍈' , level: 'basic' },
    { character: '辣', pinyin: 'là', strokes: 14, words: ['辣椒', '麻辣', '香辣'], category: 'food', emoji: '🌶️' , level: 'basic' },
    { character: '糖', pinyin: 'táng', strokes: 16, words: ['糖果', '白糖', '红糖'], category: 'food', emoji: '🍬' , level: 'basic' },
    { character: '茶', pinyin: 'chá', strokes: 9, words: ['茶叶', '喝茶', '红茶'], category: 'food', emoji: '🍵' , level: 'intermediate' },
    { character: '酒', pinyin: 'jiǔ', strokes: 10, words: ['白酒', '红酒', '酒杯'], category: 'food', emoji: '🍷' , level: 'advanced' },
    { character: '油', pinyin: 'yóu', strokes: 8, words: ['油', '汽油', '香油'], category: 'food', emoji: '🫗' , level: 'intermediate' },
    { character: '豆', pinyin: 'dòu', strokes: 7, words: ['豆子', '黄豆', '豆芽'], category: 'food', emoji: '🫘' , level: 'intermediate' },
    { character: '盐', pinyin: 'yán', strokes: 6, words: ['盐', '食盐', '咸盐'], category: 'food', emoji: '🧂' , level: 'intermediate' },
  ],
  colors: [
    { character: '红', pinyin: 'hóng', strokes: 6, words: ['红色', '火红', '红旗'], category: 'colors', emoji: '🔴' , level: 'basic' },
    { character: '黄', pinyin: 'huáng', strokes: 11, words: ['黄色', '金黄', '黄金'], category: 'colors', emoji: '🟡' , level: 'basic' },
    { character: '蓝', pinyin: 'lán', strokes: 13, words: ['蓝色', '蓝天', '蓝花'], category: 'colors', emoji: '🔵' , level: 'basic' },
    { character: '绿', pinyin: 'lǜ', strokes: 11, words: ['绿色', '绿叶', '绿草'], category: 'colors', emoji: '🟢' , level: 'basic' },
    { character: '白', pinyin: 'bái', strokes: 5, words: ['白色', '白雪', '白云'], category: 'colors', emoji: '⚪' , level: 'basic' },
    { character: '黑', pinyin: 'hēi', strokes: 12, words: ['黑色', '黑暗', '黑板'], category: 'colors', emoji: '⚫' , level: 'basic' },
    { character: '大', pinyin: 'dà', strokes: 3, words: ['大大', '巨大', '很大'], category: 'colors', emoji: '⭕' , level: 'basic' },
    { character: '小', pinyin: 'xiǎo', strokes: 3, words: ['小小', '微小', '很小'], category: 'colors', emoji: '⚪' , level: 'basic' },
    { character: '方', pinyin: 'fāng', strokes: 4, words: ['方向', '方法', '四方'], category: 'colors', emoji: '⬜' , level: 'basic' },
    { character: '圆', pinyin: 'yuán', strokes: 10, words: ['圆形', '圆满', '圆圈'], category: 'colors', emoji: '⚫' , level: 'basic' },
    { character: '长', pinyin: 'cháng', strokes: 4, words: ['长', '长短', '很长'], category: 'colors', emoji: '📏' , level: 'basic' },
    { character: '短', pinyin: 'duǎn', strokes: 11, words: ['短', '短促', '很短'], category: 'colors', emoji: '📏' , level: 'basic' },
    { character: '多', pinyin: 'duō', strokes: 6, words: ['多', '很多', '多少'], category: 'colors', emoji: '🔢' , level: 'intermediate' },
    { character: '少', pinyin: 'shǎo', strokes: 4, words: ['少', '很少', '多少'], category: 'colors', emoji: '🔢' , level: 'intermediate' },
  ],
  numbers: [
    { character: '一', pinyin: 'yī', strokes: 1, words: ['一个', '一天', '第一'], category: 'numbers', emoji: '1️⃣' , level: 'basic' },
    { character: '二', pinyin: 'èr', strokes: 2, words: ['二个', '二人', '第二'], category: 'numbers', emoji: '2️⃣' , level: 'basic' },
    { character: '三', pinyin: 'sān', strokes: 3, words: ['三个', '三人', '第三'], category: 'numbers', emoji: '3️⃣' , level: 'basic' },
    { character: '四', pinyin: 'sì', strokes: 5, words: ['四个', '四人', '第四'], category: 'numbers', emoji: '4️⃣' , level: 'basic' },
    { character: '五', pinyin: 'wǔ', strokes: 4, words: ['五个', '五人', '第五'], category: 'numbers', emoji: '5️⃣' , level: 'basic' },
    { character: '六', pinyin: 'liù', strokes: 4, words: ['六个', '六人', '第六'], category: 'numbers', emoji: '6️⃣' , level: 'basic' },
    { character: '七', pinyin: 'qī', strokes: 2, words: ['七个', '七人', '第七'], category: 'numbers', emoji: '7️⃣' , level: 'basic' },
    { character: '八', pinyin: 'bā', strokes: 2, words: ['八个', '八人', '第八'], category: 'numbers', emoji: '8️⃣' , level: 'basic' },
    { character: '九', pinyin: 'jiǔ', strokes: 2, words: ['九个', '九人', '第九'], category: 'numbers', emoji: '9️⃣' , level: 'basic' },
    { character: '十', pinyin: 'shí', strokes: 2, words: ['十个', '十人', '第十'], category: 'numbers', emoji: '🔟' , level: 'basic' },
    { character: '天', pinyin: 'tiān', strokes: 4, words: ['天气', '蓝天', '白天'], category: 'numbers', emoji: '☀️' , level: 'basic' },
    { character: '年', pinyin: 'nián', strokes: 6, words: ['年龄', '新年', '少年'], category: 'numbers', emoji: '📅' , level: 'basic' },
    { character: '月', pinyin: 'yuè', strokes: 4, words: ['月份', '一月', '月亮'], category: 'numbers', emoji: '📅' , level: 'basic' },
    { character: '日', pinyin: 'rì', strokes: 4, words: ['日子', '日子', '日子'], category: 'numbers', emoji: '📅' , level: 'basic' },
    { character: '零', pinyin: 'líng', strokes: 13, words: ['零', '零点', '零钱'], category: 'numbers', emoji: '0️⃣' , level: 'intermediate' },
    { character: '百', pinyin: 'bǎi', strokes: 6, words: ['一百', '百万', '百姓'], category: 'numbers', emoji: '💯' , level: 'intermediate' },
    { character: '千', pinyin: 'qiān', strokes: 3, words: ['一千', '千万', '千里'], category: 'numbers', emoji: '🔢' , level: 'intermediate' },
    { character: '万', pinyin: 'wàn', strokes: 3, words: ['一万', '千万', '万里'], category: 'numbers', emoji: '🔢' , level: 'intermediate' },
  ],
  daily: [
    { character: '来', pinyin: 'lái', strokes: 7, words: ['回来', '过来', '来到'], category: 'daily', emoji: '🚶' , level: 'basic' },
    { character: '去', pinyin: 'qù', strokes: 5, words: ['回去', '出去', '下去'], category: 'daily', emoji: '🏃' , level: 'basic' },
    { character: '好', pinyin: 'hǎo', strokes: 6, words: ['好人', '好事', '很好'], category: 'daily', emoji: '👍' , level: 'basic' },
    { character: '开', pinyin: 'kāi', strokes: 4, words: ['开门', '开车', '开心'], category: 'daily', emoji: '🚪' , level: 'basic' },
    { character: '看', pinyin: 'kàn', strokes: 9, words: ['看书', '看见', '看花'], category: 'daily', emoji: '👀' , level: 'basic' },
    { character: '听', pinyin: 'tīng', strokes: 7, words: ['听见', '听话', '听歌'], category: 'daily', emoji: '👂' , level: 'basic' },
    { character: '说', pinyin: 'shuō', strokes: 9, words: ['说话', '说明', '说法'], category: 'daily', emoji: '🗣️' , level: 'basic' },
    { character: '爱', pinyin: 'ài', strokes: 10, words: ['爱心', '爱人', '热爱'], category: 'daily', emoji: '❤️' , level: 'basic' },
    { character: '乐', pinyin: 'lè', strokes: 5, words: ['快乐', '欢乐', '乐园'], category: 'daily', emoji: '😊' , level: 'basic' },
    { character: '学', pinyin: 'xué', strokes: 8, words: ['学习', '学生', '同学'], category: 'daily', emoji: '📚' , level: 'basic' },
    { character: '写', pinyin: 'xiě', strokes: 5, words: ['写字', '写书', '书写'], category: 'daily', emoji: '✍️' , level: 'basic' },
    { character: '读', pinyin: 'dú', strokes: 10, words: ['读书', '阅读', '读懂'], category: 'daily', emoji: '📖' , level: 'basic' },
    { character: '吃', pinyin: 'chī', strokes: 6, words: ['吃饭', '好吃', '吃草'], category: 'daily', emoji: '🍴' , level: 'basic' },
    { character: '睡', pinyin: 'shuì', strokes: 13, words: ['睡觉', '睡眠', '睡午觉'], category: 'daily', emoji: '😴' , level: 'basic' },
    { character: '玩', pinyin: 'wán', strokes: 8, words: ['好玩', '玩耍', '玩具'], category: 'daily', emoji: '🎮' , level: 'basic' },
    { character: '想', pinyin: 'xiǎng', strokes: 13, words: ['想想', '想法', '想念'], category: 'daily', emoji: '💭' , level: 'intermediate' },
    { character: '帮', pinyin: 'bāng', strokes: 9, words: ['帮忙', '帮助', '助手'], category: 'daily', emoji: '🤝' , level: 'intermediate' },
    { character: '找', pinyin: 'zhǎo', strokes: 7, words: ['寻找', '找到', '找事'], category: 'daily', emoji: '🔍' , level: 'intermediate' },
    { character: '做', pinyin: 'zuò', strokes: 11, words: ['做', '做作业', '做事'], category: 'daily', emoji: '✅' , level: 'intermediate' },
    { character: '拿', pinyin: 'ná', strokes: 10, words: ['拿', '拿走', '拿来'], category: 'daily', emoji: '🤲' , level: 'intermediate' },
  ],
  school: [
    { character: '书', pinyin: 'shū', strokes: 4, words: ['书本', '读书', '看书'], category: 'school', emoji: '📖' , level: 'basic' },
    { character: '笔', pinyin: 'bǐ', strokes: 10, words: ['铅笔', '毛笔', '笔尖'], category: 'school', emoji: '✏️' , level: 'basic' },
    { character: '纸', pinyin: 'zhǐ', strokes: 10, words: ['纸张', '纸巾', '白纸'], category: 'school', emoji: '📄' , level: 'basic' },
    { character: '本', pinyin: 'běn', strokes: 5, words: ['书本', '作业本', '笔记本'], category: 'school', emoji: '📓' , level: 'basic' },
    { character: '包', pinyin: 'bāo', strokes: 5, words: ['书包', '包子', '红包'], category: 'school', emoji: '🎒' , level: 'basic' },
    { character: '桌', pinyin: 'zhuō', strokes: 10, words: ['桌子', '书桌', '课桌'], category: 'school', emoji: '🪑' , level: 'basic' },
    { character: '椅', pinyin: 'yǐ', strokes: 12, words: ['椅子', '桌椅', '坐椅'], category: 'school', emoji: '🪑' , level: 'basic' },
    { character: '校', pinyin: 'xiào', strokes: 10, words: ['学校', '校园', '校长'], category: 'school', emoji: '🏫' , level: 'basic' },
    { character: '课', pinyin: 'kè', strokes: 10, words: ['上课', '下课', '功课'], category: 'school', emoji: '📚' , level: 'basic' },
    { character: '堂', pinyin: 'táng', strokes: 11, words: ['课堂', '礼堂', '食堂'], category: 'school', emoji: '🏫' , level: 'basic' },
    { character: '教', pinyin: 'jiào', strokes: 11, words: ['教师', '教室', '教学'], category: 'school', emoji: '👨‍🏫' , level: 'basic' },
    { character: '师', pinyin: 'shī', strokes: 6, words: ['老师', '教师', '师父'], category: 'school', emoji: '👨‍🏫' , level: 'basic' },
    { character: '册', pinyin: 'cè', strokes: 5, words: ['画册', '书册', '图册'], category: 'school', emoji: '📕' , level: 'intermediate' },
    { character: '卷', pinyin: 'juàn', strokes: 8, words: ['卷子', '试卷', '卷起'], category: 'school', emoji: '📜' , level: 'intermediate' },
  ],
  clothes: [
    { character: '衣', pinyin: 'yī', strokes: 6, words: ['衣服', '上衣', '外衣'], category: 'clothes', emoji: '👕' , level: 'basic' },
    { character: '服', pinyin: 'fú', strokes: 8, words: ['衣服', '服务', '服装'], category: 'clothes', emoji: '👔' , level: 'basic' },
    { character: '裤', pinyin: 'kù', strokes: 12, words: ['裤子', '短裤', '长裤'], category: 'clothes', emoji: '👖' , level: 'basic' },
    { character: '鞋', pinyin: 'xié', strokes: 15, words: ['鞋子', '布鞋', '皮鞋'], category: 'clothes', emoji: '👞' , level: 'basic' },
    { character: '帽', pinyin: 'mào', strokes: 12, words: ['帽子', '草帽', '礼帽'], category: 'clothes', emoji: '🧢' , level: 'basic' },
    { character: '袜', pinyin: 'wà', strokes: 10, words: ['袜子', '丝袜', '短袜'], category: 'clothes', emoji: '🧦' , level: 'basic' },
    { character: '巾', pinyin: 'jīn', strokes: 3, words: ['毛巾', '餐巾', '红巾'], category: 'clothes', emoji: '🧣' , level: 'basic' },
    { character: '裙', pinyin: 'qún', strokes: 12, words: ['裙子', '长裙', '短裙'], category: 'clothes', emoji: '👗' , level: 'basic' },
    { character: '领', pinyin: 'lǐng', strokes: 11, words: ['领子', '红领巾', '领袖'], category: 'clothes', emoji: '🧣' , level: 'basic' },
    { character: '围', pinyin: 'wéi', strokes: 7, words: ['围巾', '包围', '围裙'], category: 'clothes', emoji: '🧣' , level: 'basic' },
    { character: '衫', pinyin: 'shān', strokes: 8, words: ['衬衫', '汗衫', '衣衫'], category: 'clothes', emoji: '👕' , level: 'intermediate' },
    { character: '夹', pinyin: 'jiā', strokes: 6, words: ['夹克', '夹衣', '夹子'], category: 'clothes', emoji: '🧥' , level: 'intermediate' },
    { character: '背', pinyin: 'bèi', strokes: 9, words: ['背心', '书包', '背包'], category: 'clothes', emoji: '🎒' , level: 'intermediate' },
  ],
  vehicles: [
    { character: '车', pinyin: 'chē', strokes: 4, words: ['汽车', '火车', '开车'], category: 'vehicles', emoji: '🚗' , level: 'basic' },
    { character: '船', pinyin: 'chuán', strokes: 11, words: ['小船', '轮船', '船儿'], category: 'vehicles', emoji: '🚢' , level: 'basic' },
    { character: '飞', pinyin: 'fēi', strokes: 3, words: ['飞机', '飞翔', '飞鸟'], category: 'vehicles', emoji: '✈️' , level: 'basic' },
    { character: '机', pinyin: 'jī', strokes: 6, words: ['飞机', '机器', '手机'], category: 'vehicles', emoji: '✈️' , level: 'basic' },
    { character: '路', pinyin: 'lù', strokes: 13, words: ['道路', '走路', '公路'], category: 'vehicles', emoji: '🛣️' , level: 'basic' },
    { character: '桥', pinyin: 'qiáo', strokes: 16, words: ['大桥', '木桥', '小桥'], category: 'vehicles', emoji: '🌉' , level: 'basic' },
    { character: '站', pinyin: 'zhàn', strokes: 10, words: ['车站', '网站', '站点'], category: 'vehicles', emoji: '🚉' , level: 'basic' },
    { character: '航', pinyin: 'háng', strokes: 10, words: ['航海', '航空', '航行'], category: 'vehicles', emoji: '⚓' , level: 'basic' },
    { character: '轮', pinyin: 'lún', strokes: 8, words: ['轮船', '车轮', '齿轮'], category: 'vehicles', emoji: '⚙️' , level: 'intermediate' },
    { character: '轨', pinyin: 'guǐ', strokes: 6, words: ['轨道', '铁轨', '路线'], category: 'vehicles', emoji: '🛤️' , level: 'intermediate' },
  ],
  places: [
    { character: '家', pinyin: 'jiā', strokes: 10, words: ['家庭', '大家', '家人'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '门', pinyin: 'mén', strokes: 3, words: ['大门', '开门', '门口'], category: 'places', emoji: '🚪' , level: 'basic' },
    { character: '户', pinyin: 'hù', strokes: 4, words: ['户口', '门户', '千家万户'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '房', pinyin: 'fáng', strokes: 8, words: ['房间', '房子', '楼房'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '间', pinyin: 'jiān', strokes: 7, words: ['时间', '房间', '中间'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '城', pinyin: 'chéng', strokes: 9, words: ['城市', '长城', '城门'], category: 'places', emoji: '🏙️' , level: 'basic' },
    { character: '村', pinyin: 'cūn', strokes: 7, words: ['村庄', '农村', '乡村'], category: 'places', emoji: '🏡' , level: 'basic' },
    { character: '店', pinyin: 'diàn', strokes: 8, words: ['商店', '店铺', '酒店'], category: 'places', emoji: '🏪' , level: 'basic' },
    { character: '市', pinyin: 'shì', strokes: 5, words: ['城市', '市场', '市长'], category: 'places', emoji: '🏙️' , level: 'basic' },
    { character: '国', pinyin: 'guó', strokes: 8, words: ['国家', '中国', '国歌'], category: 'places', emoji: '🇨🇳' , level: 'basic' },
    { character: '园', pinyin: 'yuán', strokes: 7, words: ['公园', '花园', '校园'], category: 'places', emoji: '🌳' , level: 'basic' },
    { character: '院', pinyin: 'yuàn', strokes: 9, words: ['医院', '院子', '法院'], category: 'places', emoji: '🏥' , level: 'basic' },
    { character: '楼', pinyin: 'lóu', strokes: 13, words: ['大楼', '楼房', '高楼'], category: 'places', emoji: '🏢' , level: 'intermediate' },
    { character: '宫', pinyin: 'gōng', strokes: 9, words: ['宫殿', '皇宫', '天宫'], category: 'places', emoji: '🏛️' , level: 'intermediate' },
    { character: '馆', pinyin: 'guǎn', strokes: 11, words: ['图书馆', '饭店', '博物馆'], category: 'places', emoji: '🏛️' , level: 'intermediate' },
    { character: '边', pinyin: 'biān', strokes: 5, words: ['边上', '旁边', '边边'], category: 'places', emoji: '➡️' , level: 'intermediate' },
    { character: '旁', pinyin: 'páng', strokes: 10, words: ['旁边', '旁人', '两旁'], category: 'places', emoji: '↗️' , level: 'intermediate' },
  ],
};
