// 拼音字母数据

export interface PinyinLetter {
  letter: string;
  pinyin: string;
  category: 'shengmu' | 'yunmu' | 'zhengtiren';
  examples: string[];
  emoji: string;
}

// 声母
export const shengmu: PinyinLetter[] = [
  { letter: 'b', pinyin: 'bo', category: 'shengmu', examples: ['爸爸', '宝宝', '抱抱'], emoji: '👶' },
  { letter: 'p', pinyin: 'po', category: 'shengmu', examples: ['爬', '跑', '拍'], emoji: '🏃' },
  { letter: 'm', pinyin: 'mo', category: 'shengmu', examples: ['妈妈', '猫', '摸'], emoji: '😺' },
  { letter: 'f', pinyin: 'fo', category: 'shengmu', examples: ['饭', '飞', '风'], emoji: '🍚' },
  { letter: 'd', pinyin: 'de', category: 'shengmu', examples: ['大', '弟弟', '跳舞'], emoji: '💃' },
  { letter: 't', pinyin: 'te', category: 'shengmu', examples: ['他', '太', '跳'], emoji: '🦘' },
  { letter: 'n', pinyin: 'ne', category: 'shengmu', examples: ['你', '鸟', '牛奶'], emoji: '🐦' },
  { letter: 'l', pinyin: 'le', category: 'shengmu', examples: ['来', '拉', '乐'], emoji: '😊' },
  { letter: 'g', pinyin: 'ge', category: 'shengmu', examples: ['狗', '哥哥', '瓜'], emoji: '🐕' },
  { letter: 'k', pinyin: 'ke', category: 'shengmu', examples: ['看', '哭', '开心'], emoji: '👀' },
  { letter: 'h', pinyin: 'he', category: 'shengmu', examples: ['喝', '花', '好'], emoji: '🌸' },
  { letter: 'j', pinyin: 'ji', category: 'shengmu', examples: ['鸡', '家', '姐姐'], emoji: '🐔' },
  { letter: 'q', pinyin: 'qi', category: 'shengmu', examples: ['七', '去', '气球'], emoji: '🎈' },
  { letter: 'x', pinyin: 'xi', category: 'shengmu', examples: ['西瓜', '笑', '星星'], emoji: '🍉' },
  { letter: 'zh', pinyin: 'zhi', category: 'shengmu', examples: ['蜘蛛', '猪', '纸'], emoji: '🐷' },
  { letter: 'ch', pinyin: 'chi', category: 'shengmu', examples: ['吃', '虫', '车'], emoji: '🍴' },
  { letter: 'sh', pinyin: 'shi', category: 'shengmu', examples: ['书', '手', '水'], emoji: '📚' },
  { letter: 'r', pinyin: 'ri', category: 'shengmu', examples: ['日', '热', '肉'], emoji: '☀️' },
  { letter: 'z', pinyin: 'zi', category: 'shengmu', examples: ['字', '走', '嘴'], emoji: '👄' },
  { letter: 'c', pinyin: 'ci', category: 'shengmu', examples: ['草', '菜', '擦'], emoji: '🌱' },
  { letter: 's', pinyin: 'si', category: 'shengmu', examples: ['三', '色', '山'], emoji: '⛰️' },
  { letter: 'y', pinyin: 'yi', category: 'shengmu', examples: ['一', '鱼', '月'], emoji: '🐟' },
  { letter: 'w', pinyin: 'wu', category: 'shengmu', examples: ['五', '我', '蛙'], emoji: '🐸' },
];

// 韵母 - 单韵母（修正：使用无声调或完整读音）
export const dunyunmu: PinyinLetter[] = [
  { letter: 'a', pinyin: 'a', category: 'yunmu', examples: ['阿姨', '鸭', '大'], emoji: '🦆' },
  { letter: 'o', pinyin: 'o', category: 'yunmu', examples: ['哦', '婆', '波'], emoji: '🌊' },
  { letter: 'e', pinyin: 'e', category: 'yunmu', examples: ['鹅', '额', '饿'], emoji: '🦢' },
  { letter: 'i', pinyin: 'yi', category: 'yunmu', examples: ['衣', '椅', '一'], emoji: '👕' },
  { letter: 'u', pinyin: 'wu', category: 'yunmu', examples: ['乌', '屋', '五'], emoji: '🏠' },
  { letter: 'ü', pinyin: 'yu', category: 'yunmu', examples: ['鱼', '雨', '羽'], emoji: '🌧️' },
];

// 韵母 - 复韵母（修正：使用正确读音）
export const fuyunmu: PinyinLetter[] = [
  { letter: 'ai', pinyin: 'ai', category: 'yunmu', examples: ['爱', '奶奶', '开'], emoji: '❤️' },
  { letter: 'ei', pinyin: 'ei', category: 'yunmu', examples: ['飞', '妹', '黑'], emoji: '✈️' },
  { letter: 'ui', pinyin: 'wei', category: 'yunmu', examples: ['水', '腿', '队'], emoji: '💧' },
  { letter: 'ao', pinyin: 'ao', category: 'yunmu', examples: ['袄', '宝宝', '草'], emoji: '🍚' },
  { letter: 'ou', pinyin: 'ou', category: 'yunmu', examples: ['手', '狗', '走'], emoji: '🐾' },
  { letter: 'iu', pinyin: 'you', category: 'yunmu', examples: ['牛', '球', '流'], emoji: '🎾' },
  { letter: 'ie', pinyin: 'ie', category: 'yunmu', examples: ['姐', '爷', '叶'], emoji: '🍂' },
  { letter: 'üe', pinyin: 'yue', category: 'yunmu', examples: ['月', '雪', '学'], emoji: '❄️' },
  { letter: 'er', pinyin: 'er', category: 'yunmu', examples: ['耳', '二', '儿'], emoji: '👂' },
  { letter: 'an', pinyin: 'an', category: 'yunmu', examples: ['安', '饭', '班'], emoji: '🍛' },
  { letter: 'en', pinyin: 'en', category: 'yunmu', examples: ['恩', '门', '人'], emoji: '🚪' },
  { letter: 'in', pinyin: 'yin', category: 'yunmu', examples: ['音', '金', '心'], emoji: '💛' },
  { letter: 'un', pinyin: 'wen', category: 'yunmu', examples: ['温', '论', '棍'], emoji: '🌡️' },
  { letter: 'ün', pinyin: 'yun', category: 'yunmu', examples: ['云', '匀', '军'], emoji: '☁️' },
  { letter: 'ang', pinyin: 'ang', category: 'yunmu', examples: ['昂', '方', '羊'], emoji: '🐑' },
  { letter: 'eng', pinyin: 'eng', category: 'yunmu', examples: ['灯', '风', '梦'], emoji: '💡' },
  { letter: 'ing', pinyin: 'ying', category: 'yunmu', examples: ['鹰', '星', '听'], emoji: '🦅' },
  { letter: 'ong', pinyin: 'ong', category: 'yunmu', examples: ['龙', '红', '中'], emoji: '🐲' },
];

// 整体认读音节
export const zhengtiren: PinyinLetter[] = [
  { letter: 'zhi', pinyin: 'zhi', category: 'zhengtiren', examples: ['纸', '只', '指'], emoji: '📄' },
  { letter: 'chi', pinyin: 'chi', category: 'zhengtiren', examples: ['吃', '池', '尺'], emoji: '🍽️' },
  { letter: 'shi', pinyin: 'shi', category: 'zhengtiren', examples: ['师', '诗', '十'], emoji: '📖' },
  { letter: 'ri', pinyin: 'ri', category: 'zhengtiren', examples: ['日', '入', '热'], emoji: '🌞' },
  { letter: 'zi', pinyin: 'zi', category: 'zhengtiren', examples: ['子', '字', '紫'], emoji: '💜' },
  { letter: 'ci', pinyin: 'ci', category: 'zhengtiren', examples: ['次', '词', '刺'], emoji: '🎯' },
  { letter: 'si', pinyin: 'si', category: 'zhengtiren', examples: ['思', '四', '丝'], emoji: '🎀' },
  { letter: 'yi', pinyin: 'yi', category: 'zhengtiren', examples: ['一', '衣', '医'], emoji: '👔' },
  { letter: 'wu', pinyin: 'wu', category: 'zhengtiren', examples: ['五', '无', '屋'], emoji: '🏡' },
  { letter: 'yu', pinyin: 'yu', category: 'zhengtiren', examples: ['鱼', '雨', '玉'], emoji: '💎' },
  { letter: 'ye', pinyin: 'ye', category: 'zhengtiren', examples: ['爷', '夜', '叶'], emoji: '🌙' },
  { letter: 'yue', pinyin: 'yue', category: 'zhengtiren', examples: ['月', '乐', '越'], emoji: '🌕' },
  { letter: 'yuan', pinyin: 'yuan', category: 'zhengtiren', examples: ['圆', '原', '园'], emoji: '⭕' },
  { letter: 'yin', pinyin: 'yin', category: 'zhengtiren', examples: ['音', '银', '因'], emoji: '🎵' },
  { letter: 'yun', pinyin: 'yun', category: 'zhengtiren', examples: ['云', '匀', '允'], emoji: '🌤️' },
  { letter: 'ying', pinyin: 'ying', category: 'zhengtiren', examples: ['鹰', '赢', '英'], emoji: '🏆' },
];

export const categoryNames = {
  shengmu: '声母',
  yunmu: '韵母',
  zhengtiren: '整体认读音节',
};

export const subCategoryNames = {
  dunyunmu: '单韵母',
  fuyunmu: '复韵母',
};

// 汉字学习数据
export interface HanziCharacter {
  character: string;
  pinyin: string;
  strokes: number;
  words: string[];
  category: string;
  emoji: string;
  level: 'basic' | 'intermediate' | 'advanced'; // 难度级别
}

// 常用汉字分类
export const hanziCategories = [
  { id: 'family', name: '家庭人物', emoji: '👨‍👩‍👧' },
  { id: 'nature', name: '自然事物', emoji: '🌳' },
  { id: 'animals', name: '动物世界', emoji: '🐾' },
  { id: 'body', name: '身体部位', emoji: '🖐️' },
  { id: 'food', name: '食物水果', emoji: '🍎' },
  { id: 'colors', name: '颜色形状', emoji: '🎨' },
  { id: 'numbers', name: '数字时间', emoji: '🔢' },
  { id: 'daily', name: '日常生活', emoji: '🏠' },
  { id: 'school', name: '学习用品', emoji: '📚' },
  { id: 'clothes', name: '服装衣物', emoji: '👕' },
  { id: 'vehicles', name: '交通工具', emoji: '🚗' },
  { id: 'places', name: '场所地点', emoji: '🏢' },
];

// 汉字数据
export const hanziData: Record<string, HanziCharacter[]> = {
  family: [
    { character: '爸', pinyin: 'bà', strokes: 8, words: ['爸爸', '老爸', '阿爸'], category: 'family', emoji: '👨', level: 'basic' },
    { character: '妈', pinyin: 'mā', strokes: 6, words: ['妈妈', '老妈', '姑妈'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '宝', pinyin: 'bǎo', strokes: 8, words: ['宝宝', '宝贝', '珍宝'], category: 'family', emoji: '👶' , level: 'basic' },
    { character: '哥', pinyin: 'gē', strokes: 10, words: ['哥哥', '大哥', '哥哥们'], category: 'family', emoji: '🧑' , level: 'basic' },
    { character: '姐', pinyin: 'jiě', strokes: 8, words: ['姐姐', '大姐', '姐妹'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '弟', pinyin: 'dì', strokes: 7, words: ['弟弟', '小弟', '兄弟'], category: 'family', emoji: '🧒' , level: 'basic' },
    { character: '妹', pinyin: 'mèi', strokes: 8, words: ['妹妹', '小妹', '姐妹'], category: 'family', emoji: '👧' , level: 'basic' },
    { character: '奶', pinyin: 'nǎi', strokes: 5, words: ['奶奶', '牛奶', '奶粉'], category: 'family', emoji: '👵' , level: 'basic' },
    { character: '爷', pinyin: 'yé', strokes: 6, words: ['爷爷', '大爷', '老爷'], category: 'family', emoji: '👴' , level: 'basic' },
    { character: '父', pinyin: 'fù', strokes: 4, words: ['父亲', '父母', '父子'], category: 'family', emoji: '👨' , level: 'basic' },
    { character: '母', pinyin: 'mǔ', strokes: 5, words: ['母亲', '父母', '母爱'], category: 'family', emoji: '👩' , level: 'basic' },
    { character: '亲', pinyin: 'qīn', strokes: 9, words: ['亲人', '母亲', '亲爱'], category: 'family', emoji: '👨‍👩‍👧' , level: 'basic' },
    { character: '家', pinyin: 'jiā', strokes: 10, words: ['家庭', '大家', '家人'], category: 'family', emoji: '🏠' , level: 'basic' },
    { character: '舅', pinyin: 'jiù', strokes: 13, words: ['舅舅', '大舅', '小舅'], category: 'family', emoji: '🧑' , level: 'intermediate' },
    { character: '姨', pinyin: 'yí', strokes: 9, words: ['阿姨', '大姨', '姨妈'], category: 'family', emoji: '👩' , level: 'intermediate' },
    { character: '姑', pinyin: 'gū', strokes: 8, words: ['姑姑', '小姑', '姑妈'], category: 'family', emoji: '👩' , level: 'intermediate' },
    { character: '伯', pinyin: 'bó', strokes: 7, words: ['伯父', '大伯', '伯父'], category: 'family', emoji: '👨' , level: 'intermediate' },
    { character: '孙', pinyin: 'sūn', strokes: 6, words: ['孙子', '孙女', '外孙'], category: 'family', emoji: '👶' , level: 'intermediate' },
    { character: '童', pinyin: 'tóng', strokes: 12, words: ['儿童', '童年', '童趣'], category: 'family', emoji: '👶' , level: 'intermediate' },
  ],
  nature: [
    { character: '日', pinyin: 'rì', strokes: 4, words: ['日子', '日月', '生日'], category: 'nature', emoji: '☀️' , level: 'basic' },
    { character: '月', pinyin: 'yuè', strokes: 4, words: ['月亮', '日月', '月牙'], category: 'nature', emoji: '🌙' , level: 'basic' },
    { character: '水', pinyin: 'shuǐ', strokes: 4, words: ['水果', '水杯', '喝水'], category: 'nature', emoji: '💧' , level: 'basic' },
    { character: '火', pinyin: 'huǒ', strokes: 4, words: ['火柴', '火车', '火红'], category: 'nature', emoji: '🔥' , level: 'basic' },
    { character: '山', pinyin: 'shān', strokes: 3, words: ['大山', '高山', '山脉'], category: 'nature', emoji: '⛰️' , level: 'basic' },
    { character: '风', pinyin: 'fēng', strokes: 4, words: ['大风', '风光', '风景'], category: 'nature', emoji: '🌬️' , level: 'basic' },
    { character: '雨', pinyin: 'yǔ', strokes: 8, words: ['下雨', '大雨', '小雨'], category: 'nature', emoji: '🌧️' , level: 'basic' },
    { character: '雪', pinyin: 'xuě', strokes: 11, words: ['雪花', '白雪', '下雪'], category: 'nature', emoji: '❄️' , level: 'basic' },
    { character: '云', pinyin: 'yún', strokes: 4, words: ['白云', '云朵', '乌云'], category: 'nature', emoji: '☁️' , level: 'basic' },
    { character: '花', pinyin: 'huā', strokes: 7, words: ['花朵', '花园', '花朵'], category: 'nature', emoji: '🌸' , level: 'basic' },
    { character: '树', pinyin: 'shù', strokes: 9, words: ['树木', '大树', '树林'], category: 'nature', emoji: '🌳' , level: 'basic' },
    { character: '草', pinyin: 'cǎo', strokes: 9, words: ['小草', '青草', '草地'], category: 'nature', emoji: '🌱' , level: 'basic' },
    { character: '石', pinyin: 'shí', strokes: 5, words: ['石头', '岩石', '玉石'], category: 'nature', emoji: '🪨' , level: 'basic' },
    { character: '田', pinyin: 'tián', strokes: 5, words: ['田地', '田野', '水田'], category: 'nature', emoji: '🌾' , level: 'basic' },
    { character: '冰', pinyin: 'bīng', strokes: 6, words: ['冰块', '冰雪', '冰冻'], category: 'nature', emoji: '🧊' , level: 'intermediate' },
    { character: '海', pinyin: 'hǎi', strokes: 10, words: ['大海', '海洋', '海边'], category: 'nature', emoji: '🌊' , level: 'intermediate' },
    { character: '河', pinyin: 'hé', strokes: 8, words: ['河水', '小河', '河流'], category: 'nature', emoji: '🌊' , level: 'intermediate' },
    { character: '湖', pinyin: 'hú', strokes: 12, words: ['湖水', '湖泊', '江湖'], category: 'nature', emoji: '🏞️' , level: 'intermediate' },
    { character: '雷', pinyin: 'léi', strokes: 13, words: ['雷电', '雷雨', '打雷'], category: 'nature', emoji: '⚡' , level: 'intermediate' },
    { character: '电', pinyin: 'diàn', strokes: 5, words: ['闪电', '电力', '电子'], category: 'nature', emoji: '⚡' , level: 'intermediate' },
  ],
  animals: [
    { character: '鸟', pinyin: 'niao', strokes: 5, words: ['小鸟', '飞鸟', '鸟儿'], category: 'animals', emoji: '🐦' , level: 'basic' },
    { character: '鸡', pinyin: 'ji', strokes: 7, words: ['小鸡', '公鸡', '鸡蛋'], category: 'animals', emoji: '🐔' , level: 'basic' },
    { character: '猪', pinyin: 'zhu', strokes: 11, words: ['小猪', '肥猪', '猪圈'], category: 'animals', emoji: '🐷' , level: 'basic' },
    { character: '狗', pinyin: 'gou', strokes: 8, words: ['小狗', '黄狗', '狗窝'], category: 'animals', emoji: '🐕' , level: 'basic' },
    { character: '猫', pinyin: 'mao', strokes: 11, words: ['小猫', '白猫', '猫咪'], category: 'animals', emoji: '🐱' , level: 'basic' },
    { character: '鱼', pinyin: 'yǔ', strokes: 8, words: ['小鱼', '金鱼', '鱼儿'], category: 'animals', emoji: '🐟' , level: 'basic' },
    { character: '牛', pinyin: 'niu', strokes: 4, words: ['小牛', '黄牛', '牛儿'], category: 'animals', emoji: '🐄' , level: 'basic' },
    { character: '马', pinyin: 'mā', strokes: 10, words: ['小马', '白马', '马儿'], category: 'animals', emoji: '🐴' , level: 'basic' },
    { character: '羊', pinyin: 'yang', strokes: 6, words: ['小羊', '白羊', '羊儿'], category: 'animals', emoji: '🐑' , level: 'basic' },
    { character: '兔', pinyin: 'tu', strokes: 8, words: ['兔子', '小兔', '白兔'], category: 'animals', emoji: '🐰' , level: 'basic' },
    { character: '虎', pinyin: 'hú', strokes: 8, words: ['老虎', '虎头', '小虎'], category: 'animals', emoji: '🐯' , level: 'basic' },
    { character: '狮', pinyin: 'shí', strokes: 9, words: ['狮子', '雄狮', '狮王'], category: 'animals', emoji: '🦁' , level: 'basic' },
    { character: '象', pinyin: 'xiang', strokes: 11, words: ['大象', '白象', '象牙'], category: 'animals', emoji: '🐘' , level: 'basic' },
    { character: '猴', pinyin: 'hou', strokes: 12, words: ['猴子', '小猴', '猴王'], category: 'animals', emoji: '🐵' , level: 'basic' },
    { character: '鹿', pinyin: 'lu', strokes: 11, words: ['鹿', '梅花鹿', '小鹿'], category: 'animals', emoji: '🦌' , level: 'intermediate' },
    { character: '熊', pinyin: 'xiong', strokes: 14, words: ['熊', '熊猫', '狗熊'], category: 'animals', emoji: '🐻' , level: 'intermediate' },
    { character: '狼', pinyin: 'lang', strokes: 10, words: ['狼', '狼群', '大灰狼'], category: 'animals', emoji: '🐺' , level: 'advanced' },
    { character: '虫', pinyin: 'chong', strokes: 6, words: ['虫子', '昆虫', '害虫'], category: 'animals', emoji: '🐛' , level: 'intermediate' },
    { character: '龙', pinyin: 'long', strokes: 5, words: ['龙', '龙凤', '龙灯'], category: 'animals', emoji: '🐉' , level: 'advanced' },
  ],
  body: [
    { character: '手', pinyin: 'shou', strokes: 4, words: ['大手', '小手', '双手'], category: 'body', emoji: '🖐️' , level: 'basic' },
    { character: '口', pinyin: 'kou', strokes: 3, words: ['大口', '小口', '口水'], category: 'body', emoji: '👄' , level: 'basic' },
    { character: '耳', pinyin: 'er', strokes: 6, words: ['耳朵', '左耳', '右耳'], category: 'body', emoji: '👂' , level: 'basic' },
    { character: '目', pinyin: 'mǔ', strokes: 5, words: ['目光', '目标', '目的'], category: 'body', emoji: '👁️' , level: 'basic' },
    { character: '足', pinyin: 'zu', strokes: 7, words: ['足球', '十足', '手足'], category: 'body', emoji: '🦶' , level: 'basic' },
    { character: '心', pinyin: 'xin', strokes: 4, words: ['开心', '心情', '爱心'], category: 'body', emoji: '❤️' , level: 'basic' },
    { character: '头', pinyin: 'tou', strokes: 5, words: ['头', '头顶', '石头'], category: 'body', emoji: '🗣️' , level: 'basic' },
    { character: '脸', pinyin: 'lian', strokes: 9, words: ['脸', '脸色', '洗脸'], category: 'body', emoji: '😊' , level: 'basic' },
    { character: '眼', pinyin: 'yan', strokes: 11, words: ['眼睛', '眼神', '眼光'], category: 'body', emoji: '👁️' , level: 'basic' },
    { character: '鼻', pinyin: 'bi', strokes: 14, words: ['鼻子', '鼻尖', '鼻孔'], category: 'body', emoji: '👃' , level: 'intermediate' },
    { character: '嘴', pinyin: 'zui', strokes: 16, words: ['嘴巴', '嘴角', '闭嘴'], category: 'body', emoji: '👄' , level: 'intermediate' },
    { character: '牙', pinyin: 'ya', strokes: 4, words: ['牙齿', '牙痛', '牙刷'], category: 'body', emoji: '🦷' , level: 'intermediate' },
    { character: '舌', pinyin: 'she', strokes: 6, words: ['舌头', '舌苔', '吞舌'], category: 'body', emoji: '👅' , level: 'intermediate' },
    { character: '手', pinyin: 'shou', strokes: 4, words: ['手势', '动手', '手心'], category: 'body', emoji: '🖐️' , level: 'basic' },
    { character: '指', pinyin: 'zhi', strokes: 9, words: ['手指', '指导', '指示'], category: 'body', emoji: '👆' , level: 'basic' },
    { character: '掌', pinyin: 'zhang', strokes: 12, words: ['手掌', '巴掌', '掌心'], category: 'body', emoji: '✋' , level: 'intermediate' },
    { character: '臂', pinyin: 'bi', strokes: 17, words: ['手臂', '臂膀', '双臂'], category: 'body', emoji: '💪' , level: 'intermediate' },
    { character: '肩', pinyin: 'jian', strokes: 8, words: ['肩膀', '并肩', '双肩'], category: 'body', emoji: '🤷' , level: 'intermediate' },
    { character: '胸', pinyin: 'xiong', strokes: 10, words: ['胸部', '胸脯', '胸膛'], category: 'body', emoji: '🫁' , level: 'intermediate' },
    { character: '肚', pinyin: 'du', strokes: 7, words: ['肚子', '肚皮', '肚脐'], category: 'body', emoji: '🫃' , level: 'intermediate' },
    { character: '腰', pinyin: 'yao', strokes: 13, words: ['腰', '弯腰', '腰带'], category: 'body', emoji: '🏋️' , level: 'intermediate' },
    { character: '腿', pinyin: 'tui', strokes: 13, words: ['腿', '大腿', '小腿'], category: 'body', emoji: '🦵' , level: 'intermediate' },
    { character: '脚', pinyin: 'jiao', strokes: 11, words: ['脚', '脚步', '脚步'], category: 'body', emoji: '🦶' , level: 'basic' },
  ],
  food: [
    { character: '米', pinyin: 'mi', strokes: 6, words: ['大米', '米饭', '小米'], category: 'food', emoji: '🍚' , level: 'basic' },
    { character: '饭', pinyin: 'fan', strokes: 7, words: ['吃饭', '米饭', '晚饭'], category: 'food', emoji: '🍚' , level: 'basic' },
    { character: '面', pinyin: 'mian', strokes: 9, words: ['面条', '面包', '面粉'], category: 'food', emoji: '🍜' , level: 'basic' },
    { character: '蛋', pinyin: 'dan', strokes: 9, words: ['鸡蛋', '蛋糕', '鸭蛋'], category: 'food', emoji: '🥚' , level: 'basic' },
    { character: '肉', pinyin: 'rou', strokes: 6, words: ['肉', '牛肉', '猪肉'], category: 'food', emoji: '🥩' , level: 'basic' },
    { character: '鱼', pinyin: 'yǔ', strokes: 8, words: ['鱼', '鱼肉', '金鱼'], category: 'food', emoji: '🐟' , level: 'basic' },
    { character: '鸡', pinyin: 'ji', strokes: 7, words: ['鸡肉', '公鸡', '母鸡'], category: 'food', emoji: '🍗' , level: 'basic' },
    { character: '菜', pinyin: 'cai', strokes: 11, words: ['菜', '蔬菜', '青菜'], category: 'food', emoji: '🥬' , level: 'basic' },
    { character: '果', pinyin: 'guo', strokes: 8, words: ['水果', '苹果', '果实'], category: 'food', emoji: '🍎' , level: 'basic' },
    { character: '苹果', pinyin: 'pingguo', strokes: 16, words: ['苹果', '苹果树', '苹果味'], category: 'food', emoji: '🍎' , level: 'basic' },
    { character: '香蕉', pinyin: 'xiangjiao', strokes: 20, words: ['香蕉', '香蕉皮', '香蕉味'], category: 'food', emoji: '🍌' , level: 'basic' },
    { character: '西瓜', pinyin: 'xigua', strokes: 18, words: ['西瓜', '西瓜皮', '西瓜汁'], category: 'food', emoji: '🍉' , level: 'basic' },
    { character: '葡萄', pinyin: 'putao', strokes: 20, words: ['葡萄', '葡萄干', '葡萄藤'], category: 'food', emoji: '🍇' , level: 'intermediate' },
    { character: '梨', pinyin: 'li', strokes: 11, words: ['梨', '梨子', '梨花'], category: 'food', emoji: '🍐' , level: 'basic' },
    { character: '桃', pinyin: 'tao', strokes: 10, words: ['桃', '桃子', '桃花'], category: 'food', emoji: '🍑' , level: 'basic' },
    { character: '糖', pinyin: 'tang', strokes: 16, words: ['糖', '糖果', '红糖'], category: 'food', emoji: '🍬' , level: 'intermediate' },
    { character: '盐', pinyin: 'yan', strokes: 11, words: ['盐', '食盐', '咸盐'], category: 'food', emoji: '🧂' , level: 'intermediate' },
    { character: '油', pinyin: 'you', strokes: 8, words: ['油', '菜油', '香油'], category: 'food', emoji: '🫗' , level: 'intermediate' },
    { character: '水', pinyin: 'shuǐ', strokes: 4, words: ['水', '喝水', '开水'], category: 'food', emoji: '💧' , level: 'basic' },
    { character: '茶', pinyin: 'cha', strokes: 9, words: ['茶', '茶叶', '喝茶'], category: 'food', emoji: '🍵' , level: 'intermediate' },
    { character: '奶', pinyin: 'nǎi', strokes: 5, words: ['牛奶', '奶奶', '奶粉'], category: 'food', emoji: '🥛' , level: 'basic' },
  ],
  colors: [
    { character: '红', pinyin: 'hong', strokes: 6, words: ['红色', '红花', '红红'], category: 'colors', emoji: '🔴' , level: 'basic' },
    { character: '黄', pinyin: 'huang', strokes: 11, words: ['黄色', '黄花', '黄黄'], category: 'colors', emoji: '🟡' , level: 'basic' },
    { character: '蓝', pinyin: 'lan', strokes: 13, words: ['蓝色', '蓝天', '蓝蓝'], category: 'colors', emoji: '🔵' , level: 'basic' },
    { character: '绿', pinyin: 'lu', strokes: 11, words: ['绿色', '绿叶', '绿绿'], category: 'colors', emoji: '🟢' , level: 'basic' },
    { character: '白', pinyin: 'bai', strokes: 5, words: ['白色', '白云', '白白'], category: 'colors', emoji: '⚪' , level: 'basic' },
    { character: '黑', pinyin: 'hei', strokes: 12, words: ['黑色', '黑夜', '黑黑'], category: 'colors', emoji: '⚫' , level: 'basic' },
    { character: '金', pinyin: 'jin', strokes: 8, words: ['金色', '金子', '黄金'], category: 'colors', emoji: '🟡' , level: 'intermediate' },
    { character: '银', pinyin: 'yin', strokes: 11, words: ['银色', '银子', '白银'], category: 'colors', emoji: '⚪' , level: 'intermediate' },
    { character: '紫', pinyin: 'zi', strokes: 12, words: ['紫色', '紫花', '紫紫'], category: 'colors', emoji: '🟣' , level: 'intermediate' },
    { character: '粉', pinyin: 'fen', strokes: 10, words: ['粉色', '粉红', '粉粉'], category: 'colors', emoji: '💗' , level: 'intermediate' },
    { character: '灰', pinyin: 'hui', strokes: 6, words: ['灰色', '灰色', '灰灰'], category: 'colors', emoji: '⬜' , level: 'intermediate' },
    { character: '彩', pinyin: 'cai', strokes: 11, words: ['彩色', '彩虹', '彩云'], category: 'colors', emoji: '🌈' , level: 'intermediate' },
  ],
  numbers: [
    { character: '一', pinyin: 'yí', strokes: 1, words: ['一个', '一天', '一年'], category: 'numbers', emoji: '1️⃣' , level: 'basic' },
    { character: '二', pinyin: 'er', strokes: 2, words: ['两个', '两天', '两年'], category: 'numbers', emoji: '2️⃣' , level: 'basic' },
    { character: '三', pinyin: 'san', strokes: 3, words: ['三个', '三天', '三年'], category: 'numbers', emoji: '3️⃣' , level: 'basic' },
    { character: '四', pinyin: 'si', strokes: 5, words: ['四个', '四天', '四年'], category: 'numbers', emoji: '4️⃣' , level: 'basic' },
    { character: '五', pinyin: 'wu', strokes: 4, words: ['五个', '五天', '五年'], category: 'numbers', emoji: '5️⃣' , level: 'basic' },
    { character: '六', pinyin: 'liu', strokes: 4, words: ['六个', '六天', '六年'], category: 'numbers', emoji: '6️⃣' , level: 'basic' },
    { character: '七', pinyin: 'qi', strokes: 2, words: ['七个', '七天', '七年'], category: 'numbers', emoji: '7️⃣' , level: 'basic' },
    { character: '八', pinyin: 'bà', strokes: 2, words: ['八个', '八天', '八年'], category: 'numbers', emoji: '8️⃣' , level: 'basic' },
    { character: '九', pinyin: 'jiù', strokes: 2, words: ['九个', '九天', '九年'], category: 'numbers', emoji: '9️⃣' , level: 'basic' },
    { character: '十', pinyin: 'shí', strokes: 2, words: ['十个', '十天', '十年'], category: 'numbers', emoji: '🔟' , level: 'basic' },
    { character: '百', pinyin: 'bai', strokes: 6, words: ['百', '一百', '百姓'], category: 'numbers', emoji: '💯' , level: 'intermediate' },
    { character: '千', pinyin: 'qian', strokes: 3, words: ['千', '一千', '千万'], category: 'numbers', emoji: '🔢' , level: 'intermediate' },
    { character: '万', pinyin: 'wan', strokes: 3, words: ['万', '一万', '千万'], category: 'numbers', emoji: '🔢' , level: 'intermediate' },
  ],
  daily: [
    { character: '日', pinyin: 'rì', strokes: 4, words: ['日子', '日月', '生日'], category: 'daily', emoji: '📅' , level: 'basic' },
    { character: '月', pinyin: 'yuè', strokes: 4, words: ['月亮', '日月', '月牙'], category: 'daily', emoji: '📅' , level: 'basic' },
    { character: '年', pinyin: 'nian', strokes: 6, words: ['年', '一年', '新年'], category: 'daily', emoji: '📅' , level: 'basic' },
    { character: '天', pinyin: 'tián', strokes: 4, words: ['天空', '白天', '蓝天'], category: 'daily', emoji: '☀️' , level: 'basic' },
    { character: '早', pinyin: 'zao', strokes: 6, words: ['早上', '早起', '早班'], category: 'daily', emoji: '🌅' , level: 'basic' },
    { character: '晚', pinyin: 'wan', strokes: 11, words: ['晚上', '晚安', '晚报'], category: 'daily', emoji: '🌙' , level: 'basic' },
    { character: '午', pinyin: 'wu', strokes: 4, words: ['中午', '午饭', '午后'], category: 'daily', emoji: '☀️' , level: 'basic' },
    { character: '夜', pinyin: 'yé', strokes: 8, words: ['夜晚', '半夜', '深夜'], category: 'daily', emoji: '🌙' , level: 'basic' },
    { character: '今', pinyin: 'jin', strokes: 4, words: ['今天', '今年', '如今'], category: 'daily', emoji: '📅' , level: 'basic' },
    { character: '明', pinyin: 'ming', strokes: 8, words: ['明天', '明年', '明白'], category: 'daily', emoji: '📅' , level: 'basic' },
    { character: '昨', pinyin: 'zuo', strokes: 9, words: ['昨天', '昨晚', '昨日'], category: 'daily', emoji: '📅' , level: 'intermediate' },
    { character: '时', pinyin: 'shí', strokes: 7, words: ['时间', '时候', '小时'], category: 'daily', emoji: '⏰' , level: 'intermediate' },
    { character: '钟', pinyin: 'zhong', strokes: 9, words: ['时钟', '闹钟', '钟表'], category: 'daily', emoji: '⏰' , level: 'intermediate' },
    { character: '分', pinyin: 'fen', strokes: 4, words: ['分钟', '分开', '分开'], category: 'daily', emoji: '⏰' , level: 'intermediate' },
  ],
  school: [
    { character: '书', pinyin: 'shù', strokes: 4, words: ['书本', '书包', '读书'], category: 'school', emoji: '📚' , level: 'basic' },
    { character: '笔', pinyin: 'bi', strokes: 10, words: ['铅笔', '毛笔', '画笔'], category: 'school', emoji: '✏️' , level: 'basic' },
    { character: '纸', pinyin: 'zhi', strokes: 7, words: ['纸张', '白纸', '纸巾'], category: 'school', emoji: '📄' , level: 'basic' },
    { character: '字', pinyin: 'zi', strokes: 6, words: ['字', '汉字', '写字'], category: 'school', emoji: '📝' , level: 'basic' },
    { character: '课', pinyin: 'ke', strokes: 10, words: ['上课', '下课', '课堂'], category: 'school', emoji: '📖' , level: 'basic' },
    { character: '学', pinyin: 'xuě', strokes: 8, words: ['学习', '学生', '上学'], category: 'school', emoji: '🎓' , level: 'basic' },
    { character: '校', pinyin: 'xiao', strokes: 10, words: ['学校', '校长', '校园'], category: 'school', emoji: '🏫' , level: 'basic' },
    { character: '师', pinyin: 'shí', strokes: 6, words: ['老师', '师生', '师父'], category: 'school', emoji: '👨‍🏫' , level: 'basic' },
    { character: '生', pinyin: 'sheng', strokes: 5, words: ['学生', '生命', '生活'], category: 'school', emoji: '🎓' , level: 'basic' },
    { character: '题', pinyin: 'ti', strokes: 12, words: ['题目', '问题', '答题'], category: 'school', emoji: '❓' , level: 'intermediate' },
    { character: '答', pinyin: 'da', strokes: 9, words: ['答案', '回答', '答题'], category: 'school', emoji: '✅' , level: 'intermediate' },
    { character: '考', pinyin: 'kao', strokes: 6, words: ['考试', '考场', '考生'], category: 'school', emoji: '📝' , level: 'intermediate' },
  ],
  clothes: [
    { character: '衣', pinyin: 'yí', strokes: 6, words: ['衣服', '上衣', '雨衣'], category: 'clothes', emoji: '👕' , level: 'basic' },
    { character: '裤', pinyin: 'ku', strokes: 12, words: ['裤子', '短裤', '长裤'], category: 'clothes', emoji: '👖' , level: 'basic' },
    { character: '鞋', pinyin: 'xie', strokes: 15, words: ['鞋子', '皮鞋', '运动鞋'], category: 'clothes', emoji: '👟' , level: 'basic' },
    { character: '帽', pinyin: 'mao', strokes: 12, words: ['帽子', '礼帽', '草帽'], category: 'clothes', emoji: '🧢' , level: 'basic' },
    { character: '袜', pinyin: 'wa', strokes: 10, words: ['袜子', '短袜', '长袜'], category: 'clothes', emoji: '🧦' , level: 'basic' },
    { character: '巾', pinyin: 'jin', strokes: 3, words: ['毛巾', '围巾', '手巾'], category: 'clothes', emoji: '🧣' , level: 'intermediate' },
    { character: '带', pinyin: 'dai', strokes: 9, words: ['腰带', '皮带', '带来'], category: 'clothes', emoji: '🎗️' , level: 'intermediate' },
    { character: '扣', pinyin: 'kou', strokes: 6, words: ['扣子', '纽扣', '扣上'], category: 'clothes', emoji: '🔘' , level: 'intermediate' },
  ],
  vehicles: [
    { character: '车', pinyin: 'che', strokes: 4, words: ['汽车', '火车', '马车'], category: 'vehicles', emoji: '🚗' , level: 'basic' },
    { character: '船', pinyin: 'chuan', strokes: 11, words: ['船', '小船', '轮船'], category: 'vehicles', emoji: '🚢' , level: 'basic' },
    { character: '飞机', pinyin: 'feiji', strokes: 18, words: ['飞机', '开飞机', '坐飞机'], category: 'vehicles', emoji: '✈️' , level: 'basic' },
    { character: '火车', pinyin: 'huoche', strokes: 16, words: ['火车', '坐火车', '开火车'], category: 'vehicles', emoji: '🚂' , level: 'basic' },
    { character: '汽车', pinyin: 'qiche', strokes: 16, words: ['汽车', '开汽车', '坐汽车'], category: 'vehicles', emoji: '🚗' , level: 'basic' },
    { character: '自行车', pinyin: 'zixingche', strokes: 24, words: ['自行车', '骑自行车', '自行车道'], category: 'vehicles', emoji: '🚲' , level: 'intermediate' },
    { character: '摩托', pinyin: 'motuo', strokes: 20, words: ['摩托', '摩托车', '开摩托'], category: 'vehicles', emoji: '🏍️' , level: 'intermediate' },
  ],
  places: [
    { character: '家', pinyin: 'jiā', strokes: 10, words: ['家庭', '大家', '家人'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '门', pinyin: 'men', strokes: 3, words: ['门口', '大门', '开门'], category: 'places', emoji: '🚪' , level: 'basic' },
    { character: '窗', pinyin: 'chuang', strokes: 12, words: ['窗户', '开窗', '关窗'], category: 'places', emoji: '🪟' , level: 'basic' },
    { character: '房', pinyin: 'fang', strokes: 8, words: ['房子', '房间', '书房'], category: 'places', emoji: '🏠' , level: 'basic' },
    { character: '路', pinyin: 'lu', strokes: 13, words: ['道路', '路上', '走路'], category: 'places', emoji: '🛣️' , level: 'basic' },
    { character: '桥', pinyin: 'qiao', strokes: 10, words: ['桥', '大桥', '小桥'], category: 'places', emoji: '🌉' , level: 'intermediate' },
    { character: '站', pinyin: 'zhan', strokes: 10, words: ['车站', '站台', '站点'], category: 'places', emoji: '🚉' , level: 'intermediate' },
    { character: '场', pinyin: 'chang', strokes: 6, words: ['广场', '操场', '球场'], category: 'places', emoji: '🏟️' , level: 'intermediate' },
    { character: '园', pinyin: 'yuan', strokes: 7, words: ['公园', '花园', '校园'], category: 'places', emoji: '🌳' , level: 'basic' },
    { character: '街', pinyin: 'jiě', strokes: 12, words: ['街道', '街头', '街上'], category: 'places', emoji: '🛒' , level: 'intermediate' },
    { character: '店', pinyin: 'diàn', strokes: 8, words: ['商店', '书店', '饭店'], category: 'places', emoji: '🏪' , level: 'intermediate' },
    { character: '校', pinyin: 'xiao', strokes: 10, words: ['学校', '校长', '校园'], category: 'places', emoji: '🏫' , level: 'basic' },
  ],
};
