// 三字经数据
// 经典蒙学读物，每句三字，朗朗上口

export interface SanziJingSection {
  id: string;
  title: string;
  content: string; // 原文
  pinyin: string; // 拼音
  translation?: string; // 白话翻译
  characters: SanziJingCharacter[];
  difficulty: 'basic' | 'intermediate' | 'advanced';
}

export interface SanziJingCharacter {
  char: string;
  pinyin: string;
  level: 'basic' | 'intermediate' | 'advanced';
  words: string[];
  meaning: string;
}

// 三字经完整数据（全文，共55段）
export const sanziJingSections: SanziJingSection[] = [
  // 第一段：教育启蒙
  {
    id: 'section-1',
    title: '人之初',
    content: '人之初，性本善。性相近，习相远。',
    pinyin: 'rén zhī chū, xìng běn shàn. xìng xiāng jìn, xí xiāng yuǎn.',
    translation: '人出生时，天性本来就是善良的。人的本性都很相近，但后天的习性使大家相差很远。',
    difficulty: 'basic',
    characters: [
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人生', '人们'], meaning: '人类' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '初', pinyin: 'chū', level: 'basic', words: ['初一', '初次'], meaning: '开始' },
      { char: '性', pinyin: 'xìng', level: 'basic', words: ['性格', '本性'], meaning: '本性' },
      { char: '本', pinyin: 'běn', level: 'basic', words: ['本来', '根本'], meaning: '本来' },
      { char: '善', pinyin: 'shàn', level: 'basic', words: ['善良', '友善'], meaning: '善良' },
      { char: '相', pinyin: 'xiāng', level: 'basic', words: ['相互', '相信'], meaning: '互相' },
      { char: '近', pinyin: 'jìn', level: 'basic', words: ['接近', '最近'], meaning: '相近' },
      { char: '习', pinyin: 'xí', level: 'basic', words: ['学习', '习惯'], meaning: '习染' },
      { char: '远', pinyin: 'yuǎn', level: 'basic', words: ['远方', '遥远'], meaning: '相差远' },
      { char: '苟', pinyin: 'gǒu', level: 'intermediate', words: ['苟且'], meaning: '如果' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教育' },
      { char: '乃', pinyin: 'nǎi', level: 'intermediate', words: ['乃是'], meaning: '就' },
      { char: '迁', pinyin: 'qiān', level: 'intermediate', words: ['变迁', '搬迁'], meaning: '改变' },
    ]
  },
  // 第二段：教育的重要性
  {
    id: 'section-2',
    title: '教之道',
    content: '苟不教，性乃迁。教之道，贵以专。',
    pinyin: 'gǒu bù jiào, xìng nǎi qiān. jiào zhī dào, guì yǐ zhuān.',
    translation: '如果不进行教育，人的本性就会发生变化。教育的方法，关键在于专心致志。',
    difficulty: 'basic',
    characters: [
      { char: '苟', pinyin: 'gǒu', level: 'intermediate', words: ['苟且'], meaning: '如果' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教育' },
      { char: '性', pinyin: 'xìng', level: 'basic', words: ['性格', '本性'], meaning: '本性' },
      { char: '乃', pinyin: 'nǎi', level: 'intermediate', words: ['乃是'], meaning: '就' },
      { char: '迁', pinyin: 'qiān', level: 'intermediate', words: ['变迁', '搬迁'], meaning: '改变' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '道', pinyin: 'dào', level: 'basic', words: ['道理', '道路'], meaning: '方法' },
      { char: '贵', pinyin: 'guì', level: 'basic', words: ['珍贵', '富贵'], meaning: '重要' },
      { char: '以', pinyin: 'yǐ', level: 'basic', words: ['以便', '以及'], meaning: '用' },
      { char: '专', pinyin: 'zhuān', level: 'basic', words: ['专心', '专业'], meaning: '专一' },
      { char: '昔', pinyin: 'xī', level: 'intermediate', words: ['昔日', '往昔'], meaning: '从前' },
      { char: '孟', pinyin: 'mèng', level: 'intermediate', words: ['孟子', '孟母'], meaning: '孟母' },
      { char: '母', pinyin: 'mǔ', level: 'basic', words: ['母亲', '父母'], meaning: '母亲' },
      { char: '择', pinyin: 'zé', level: 'basic', words: ['选择', '抉择'], meaning: '选择' },
    ]
  },
  // 第三段：孟母三迁
  {
    id: 'section-3',
    title: '孟母三迁',
    content: '昔孟母，择邻处。子不学，断机杼。',
    pinyin: 'xī mèng mǔ, zé lín chǔ. zǐ bù xué, duàn jī zhù.',
    translation: '过去孟子的母亲选择良好的环境居住，为了培养儿子的品德。孟子逃学回家，母亲剪断织布来教育他。',
    difficulty: 'intermediate',
    characters: [
      { char: '昔', pinyin: 'xī', level: 'intermediate', words: ['昔日', '往昔'], meaning: '从前' },
      { char: '孟', pinyin: 'mèng', level: 'intermediate', words: ['孟子', '孟母'], meaning: '孟母' },
      { char: '母', pinyin: 'mǔ', level: 'basic', words: ['母亲', '父母'], meaning: '母亲' },
      { char: '择', pinyin: 'zé', level: 'basic', words: ['选择', '抉择'], meaning: '选择' },
      { char: '邻', pinyin: 'lín', level: 'basic', words: ['邻居', '邻里'], meaning: '邻居' },
      { char: '处', pinyin: 'chǔ', level: 'basic', words: ['住处', '相处'], meaning: '居住' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '孩子' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '断', pinyin: 'duàn', level: 'basic', words: ['断开', '判断'], meaning: '剪断' },
      { char: '机', pinyin: 'jī', level: 'basic', words: ['机会', '机器'], meaning: '织布机' },
      { char: '杼', pinyin: 'zhù', level: 'advanced', words: ['机杼'], meaning: '梭子' },
      { char: '窦', pinyin: 'dòu', level: 'advanced', words: ['窦燕山'], meaning: '窦燕山' },
      { char: '燕', pinyin: 'yān', level: 'intermediate', words: ['燕子', '燕山'], meaning: '燕山' },
      { char: '山', pinyin: 'shān', level: 'basic', words: ['高山', '山水'], meaning: '山' },
    ]
  },
  // 第四段：窦燕山教子
  {
    id: 'section-4',
    title: '窦燕山',
    content: '窦燕山，有义方。教五子，名俱扬。',
    pinyin: 'dòu yān shān, yǒu yì fāng. jiào wǔ zǐ, míng jù yáng.',
    translation: '窦燕山教育有方，五个儿子都很有成就。养育孩子不教育，是父亲的过错。',
    difficulty: 'intermediate',
    characters: [
      { char: '窦', pinyin: 'dòu', level: 'advanced', words: ['窦燕山'], meaning: '窦燕山' },
      { char: '燕', pinyin: 'yān', level: 'intermediate', words: ['燕子', '燕山'], meaning: '燕山' },
      { char: '山', pinyin: 'shān', level: 'basic', words: ['高山', '山水'], meaning: '山' },
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '好的' },
      { char: '方', pinyin: 'fāng', level: 'basic', words: ['方法', '方向'], meaning: '方法' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教育' },
      { char: '五', pinyin: 'wǔ', level: 'basic', words: ['五子', '五个'], meaning: '五个' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
      { char: '名', pinyin: 'míng', level: 'basic', words: ['名声', '名字'], meaning: '名声' },
      { char: '俱', pinyin: 'jù', level: 'advanced', words: ['俱全'], meaning: '都' },
      { char: '扬', pinyin: 'yáng', level: 'basic', words: ['宣扬', '发扬'], meaning: '显扬' },
      { char: '养', pinyin: 'yǎng', level: 'basic', words: ['养育', '培养'], meaning: '养育' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父亲' },
    ]
  },
  // 第五段：教育责任
  {
    id: 'section-5',
    title: '养不父',
    content: '养不教，父之过。教不严，师之惰。',
    pinyin: 'yǎng bù jiào, fù zhī guò. jiào bù yán, shī zhī duò.',
    translation: '教育不严格，是老师的懒惰。孩子不学习，是不对的。少年时代不学习，年老时还能有什么作为呢？',
    difficulty: 'basic',
    characters: [
      { char: '养', pinyin: 'yǎng', level: 'basic', words: ['养育', '培养'], meaning: '养育' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教育' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父亲' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '过', pinyin: 'guò', level: 'basic', words: ['过错', '经过'], meaning: '过错' },
      { char: '师', pinyin: 'shī', level: 'basic', words: ['老师', '师父'], meaning: '老师' },
      { char: '惰', pinyin: 'duò', level: 'intermediate', words: ['懒惰'], meaning: '怠惰' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '孩子' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '非', pinyin: 'fēi', level: 'basic', words: ['是非', '非凡'], meaning: '过错' },
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '小时候' },
      { char: '时', pinyin: 'shí', level: 'basic', words: ['时间', '时候'], meaning: '时候' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
    ]
  },
  // 第六段：学习时机
  {
    id: 'section-6',
    title: '子不学',
    content: '子不学，非所宜。幼不学，老何为。',
    pinyin: 'zǐ bù xué, fēi suǒ yí. yòu bù xué, lǎo hé wéi.',
    translation: '玉石不雕琢，不能成为精美的器物。人不学习，就不懂得道理和道德。',
    difficulty: 'basic',
    characters: [
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '孩子' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '非', pinyin: 'fēi', level: 'basic', words: ['是非', '非凡'], meaning: '不对' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '适宜' },
      { char: '宜', pinyin: 'yí', level: 'basic', words: ['适宜', '应该'], meaning: '应该' },
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '小时候' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '老', pinyin: 'lǎo', level: 'basic', words: ['老人', '年老'], meaning: '年老' },
      { char: '何', pinyin: 'hé', level: 'basic', words: ['如何', '何人'], meaning: '什么' },
      { char: '为', pinyin: 'wéi', level: 'basic', words: ['作为', '行为'], meaning: '作为' },
      { char: '玉', pinyin: 'yù', level: 'basic', words: ['玉石', '宝玉'], meaning: '玉石' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '琢', pinyin: 'zhuó', level: 'intermediate', words: ['琢磨'], meaning: '雕琢' },
    ]
  },
  // 第七段：琢玉之理
  {
    id: 'section-7',
    title: '玉不琢',
    content: '玉不琢，不成器。人不学，不知义。',
    pinyin: 'yù bù zhuó, bù chéng qì. rén bù xué, bù zhī yì.',
    translation: '作为儿子，要孝顺父母。作为臣子，要忠诚君主。作为兄弟，要友爱。',
    difficulty: 'basic',
    characters: [
      { char: '玉', pinyin: 'yù', level: 'basic', words: ['玉石', '宝玉'], meaning: '玉石' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '琢', pinyin: 'zhuó', level: 'intermediate', words: ['琢磨'], meaning: '雕琢' },
      { char: '成', pinyin: 'chéng', level: 'basic', words: ['成功', '成为'], meaning: '成为' },
      { char: '器', pinyin: 'qì', level: 'basic', words: ['机器', '器皿'], meaning: '有用的器物' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '知', pinyin: 'zhī', level: 'basic', words: ['知道', '知识'], meaning: '懂得' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '意义'], meaning: '道理' },
      { char: '为', pinyin: 'wéi', level: 'basic', words: ['作为', '行为'], meaning: '是' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
    ]
  },
  // 第八段：为人之道
  {
    id: 'section-8',
    title: '为人子',
    content: '为人子，方少时。亲师友，习礼仪。',
    pinyin: 'wéi rén zǐ, fāng shǎo shí. qīn shī yǒu, xí lǐ yí.',
    translation: '要尊敬师长，和朋友和睦相处。要尊敬长辈，爱护晚辈。',
    difficulty: 'basic',
    characters: [
      { char: '为', pinyin: 'wéi', level: 'basic', words: ['作为', '行为'], meaning: '是' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
      { char: '方', pinyin: 'fāng', level: 'basic', words: ['方正', '方才'], meaning: '正当' },
      { char: '少', pinyin: 'shǎo', level: 'basic', words: ['少年', '少见'], meaning: '年少' },
      { char: '时', pinyin: 'shí', level: 'basic', words: ['时间', '时候'], meaning: '时候' },
      { char: '亲', pinyin: 'qīn', level: 'basic', words: ['亲近', '亲人'], meaning: '亲近' },
      { char: '师', pinyin: 'shī', level: 'basic', words: ['老师', '师父'], meaning: '老师' },
      { char: '友', pinyin: 'yǒu', level: 'basic', words: ['朋友', '友好'], meaning: '朋友' },
      { char: '习', pinyin: 'xí', level: 'basic', words: ['学习', '习惯'], meaning: '学习' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼仪' },
      { char: '仪', pinyin: 'yí', level: 'basic', words: ['仪式', '仪表'], meaning: '礼节' },
      { char: '香', pinyin: 'xiāng', level: 'basic', words: ['香水', '香气'], meaning: '香' },
      { char: '九', pinyin: 'jiǔ', level: 'basic', words: ['九岁', '九个'], meaning: '九' },
    ]
  },
  // 第九段：黄香温席
  {
    id: 'section-9',
    title: '香九龄',
    content: '香九龄，能温席。孝于亲，所当执。',
    pinyin: 'xiāng jiǔ líng, néng wēn xí. xiào yú qīn, suǒ dāng zhí.',
    translation: '九和十，十和百，百和千，千和万。这是基本的数理知识。',
    difficulty: 'intermediate',
    characters: [
      { char: '香', pinyin: 'xiāng', level: 'basic', words: ['香水', '香气'], meaning: '黄香' },
      { char: '九', pinyin: 'jiǔ', level: 'basic', words: ['九岁', '九个'], meaning: '九岁' },
      { char: '龄', pinyin: 'líng', level: 'intermediate', words: ['年龄', '高龄'], meaning: '岁' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能够' },
      { char: '温', pinyin: 'wēn', level: 'basic', words: ['温暖', '温度'], meaning: '温热' },
      { char: '席', pinyin: 'xí', level: 'basic', words: ['席子', '出席'], meaning: '席子' },
      { char: '孝', pinyin: 'xiào', level: 'basic', words: ['孝顺', '孝道'], meaning: '孝顺' },
      { char: '于', pinyin: 'yú', level: 'basic', words: ['关于', '由于'], meaning: '对' },
      { char: '亲', pinyin: 'qīn', level: 'basic', words: ['亲近', '亲人'], meaning: '父母' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '应该' },
      { char: '当', pinyin: 'dāng', level: 'basic', words: ['应当', '当时'], meaning: '应该' },
      { char: '执', pinyin: 'zhí', level: 'intermediate', words: ['执行', '坚持'], meaning: '执行' },
      { char: '融', pinyin: 'róng', level: 'intermediate', words: ['融洽', '融合'], meaning: '孔融' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四岁', '四个'], meaning: '四岁' },
      { char: '岁', pinyin: 'suì', level: 'basic', words: ['岁月', '岁数'], meaning: '岁' },
    ]
  },
  // 第十段：孔融让梨
  {
    id: 'section-10',
    title: '融四岁',
    content: '融四岁，能让梨。弟于长，宜先知。',
    pinyin: 'róng sì suì, néng ràng lí. dì yú zhǎng, yí xiān zhī.',
    translation: '三才者，是指天、地、人。三光者，是指日、月、星。',
    difficulty: 'intermediate',
    characters: [
      { char: '融', pinyin: 'róng', level: 'intermediate', words: ['融洽', '融合'], meaning: '孔融' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四岁', '四个'], meaning: '四岁' },
      { char: '岁', pinyin: 'suì', level: 'basic', words: ['岁月', '岁数'], meaning: '岁' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能够' },
      { char: '让', pinyin: 'ràng', level: 'basic', words: ['谦让', '礼让'], meaning: '谦让' },
      { char: '梨', pinyin: 'lí', level: 'basic', words: ['梨子', '梨花'], meaning: '梨子' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '弟弟' },
      { char: '于', pinyin: 'yú', level: 'basic', words: ['关于', '由于'], meaning: '对' },
      { char: '长', pinyin: 'zhǎng', level: 'basic', words: ['长辈', '长大'], meaning: '兄长' },
      { char: '宜', pinyin: 'yí', level: 'basic', words: ['适宜', '应该'], meaning: '应该' },
      { char: '先', pinyin: 'xiān', level: 'basic', words: ['先知', '先进'], meaning: '先' },
      { char: '知', pinyin: 'zhī', level: 'basic', words: ['知道', '知识'], meaning: '知道' },
      { char: '首', pinyin: 'shǒu', level: 'basic', words: ['首先', '首长'], meaning: '首先' },
      { char: '孝', pinyin: 'xiào', level: 'basic', words: ['孝顺', '孝道'], meaning: '孝顺' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '悌道' },
    ]
  },
  // 第十一段：孝悌之理
  {
    id: 'section-11',
    title: '首孝弟',
    content: '首孝弟，次见闻。知某数，识某文。',
    pinyin: 'shǒu xiào dì, cì jiàn wén. zhī mǒu shù, shí mǒu wén.',
    difficulty: 'basic',
    characters: [
      { char: '首', pinyin: 'shǒu', level: 'basic', words: ['首先', '首长'], meaning: '首先' },
      { char: '孝', pinyin: 'xiào', level: 'basic', words: ['孝顺', '孝道'], meaning: '孝顺' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '悌道' },
      { char: '次', pinyin: 'cì', level: 'basic', words: ['次要', '次数'], meaning: '其次' },
      { char: '见', pinyin: 'jiàn', level: 'basic', words: ['看见', '意见'], meaning: '所见' },
      { char: '闻', pinyin: 'wén', level: 'basic', words: ['新闻', '闻名'], meaning: '所闻' },
      { char: '知', pinyin: 'zhī', level: 'basic', words: ['知道', '知识'], meaning: '知道' },
      { char: '某', pinyin: 'mǒu', level: 'basic', words: ['某人', '某个'], meaning: '某' },
      { char: '数', pinyin: 'shù', level: 'basic', words: ['数字', '数学'], meaning: '算术' },
      { char: '识', pinyin: 'shí', level: 'basic', words: ['认识', '知识'], meaning: '认识' },
      { char: '一', pinyin: 'yī', level: 'basic', words: ['一个', '第一'], meaning: '一' },
      { char: '而', pinyin: 'ér', level: 'basic', words: ['而且', '然而'], meaning: '而' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '百', pinyin: 'bǎi', level: 'basic', words: ['百个', '一百'], meaning: '百' },
      { char: '千', pinyin: 'qiān', level: 'basic', words: ['千个', '一千'], meaning: '千' },
    ]
  },
  // 第十二段：数字
  {
    id: 'section-12',
    title: '一而十',
    content: '一而十，十而百。百而千，千而万。',
    pinyin: 'yī ér shí, shí ér bǎi. bǎi ér qiān, qiān ér wàn.',
    difficulty: 'basic',
    characters: [
      { char: '一', pinyin: 'yī', level: 'basic', words: ['一个', '第一'], meaning: '一' },
      { char: '而', pinyin: 'ér', level: 'basic', words: ['而且', '然而'], meaning: '而' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '百', pinyin: 'bǎi', level: 'basic', words: ['百个', '一百'], meaning: '百' },
      { char: '千', pinyin: 'qiān', level: 'basic', words: ['千个', '一千'], meaning: '千' },
      { char: '万', pinyin: 'wàn', level: 'basic', words: ['万个', '一万'], meaning: '万' },
      { char: '三', pinyin: 'sān', level: 'basic', words: ['三个', '第三'], meaning: '三' },
      { char: '才', pinyin: 'cái', level: 'basic', words: ['才能', '刚才'], meaning: '才' },
      { char: '光', pinyin: 'guāng', level: 'basic', words: ['光芒', '光明'], meaning: '是' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四个', '第四'], meaning: '四' },
      { char: '时', pinyin: 'shí', level: 'basic', words: ['时间', '时候'], meaning: '时候' },
      { char: '习', pinyin: 'xí', level: 'basic', words: ['学习', '习惯'], meaning: '学习' },
      { char: '致', pinyin: 'zhì', level: 'intermediate', words: ['导致', '致使'], meaning: '达到' },
      { char: '八', pinyin: 'bā', level: 'basic', words: ['八个', '第八'], meaning: '八' },
    ]
  },
  // 第十三段：学习时机
  {
    id: 'section-13',
    title: '三才者',
    content: '三才者，天地人。三光者，日月星。',
    pinyin: 'sān cái zhě, tiān dì rén. sān guāng zhě, rì yuè xīng.',
    difficulty: 'basic',
    characters: [
      { char: '三', pinyin: 'sān', level: 'basic', words: ['三个', '第三'], meaning: '三' },
      { char: '才', pinyin: 'cái', level: 'basic', words: ['才能', '刚才'], meaning: '才' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
      { char: '天', pinyin: 'tiān', level: 'basic', words: ['天空', '白天'], meaning: '天' },
      { char: '地', pinyin: 'dì', level: 'basic', words: ['大地', '土地'], meaning: '地' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '光', pinyin: 'guāng', level: 'basic', words: ['光芒', '光明'], meaning: '光' },
      { char: '日', pinyin: 'rì', level: 'basic', words: ['太阳', '日子'], meaning: '太阳' },
      { char: '月', pinyin: 'yuè', level: 'basic', words: ['月亮', '月份'], meaning: '月亮' },
      { char: '星', pinyin: 'xīng', level: 'basic', words: ['星星', '行星'], meaning: '星星' },
      { char: '三', pinyin: 'sān', level: 'basic', words: ['三个', '第三'], meaning: '三' },
      { char: '纲', pinyin: 'gāng', level: 'intermediate', words: ['纲领'], meaning: '纲领' },
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫' },
      { char: '君', pinyin: 'jūn', level: 'basic', words: ['君子', '君主'], meaning: '君臣' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父子' },
    ]
  },
  // 第十四段：三纲
  {
    id: 'section-14',
    title: '三纲者',
    content: '三纲者，君臣义。父子亲，夫妇顺。',
    pinyin: 'sān gāng zhě, jūn chén yì. fù zǐ qīn, fū fù shùn.',
    difficulty: 'intermediate',
    characters: [
      { char: '三', pinyin: 'sān', level: 'basic', words: ['三个', '第三'], meaning: '三' },
      { char: '纲', pinyin: 'gāng', level: 'intermediate', words: ['纲领'], meaning: '纲领' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
      { char: '君', pinyin: 'jūn', level: 'basic', words: ['君子', '君主'], meaning: '君' },
      { char: '臣', pinyin: 'chén', level: 'basic', words: ['大臣', '臣子'], meaning: '臣' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '亲', pinyin: 'qīn', level: 'basic', words: ['亲近', '亲人'], meaning: '亲' },
      { char: '夫', pinyin: 'fū', level: 'basic', words: ['丈夫', '农夫'], meaning: '夫' },
      { char: '妇', pinyin: 'fù', level: 'basic', words: ['妇女', '夫妇'], meaning: '妇' },
      { char: '顺', pinyin: 'shùn', level: 'basic', words: ['顺利', '顺从'], meaning: '顺' },
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '春', pinyin: 'chūn', level: 'basic', words: ['春天', '春季'], meaning: '春' },
      { char: '夏', pinyin: 'xià', level: 'basic', words: ['夏天', '夏季'], meaning: '夏' },
    ]
  },
  // 第十五段：四季
  {
    id: 'section-15',
    title: '曰春夏',
    content: '曰春夏，曰秋冬。此四时，运不穷。',
    pinyin: 'yuē chūn xià, yuē qiū dōng. cǐ sì shí, yùn bù qióng.',
    difficulty: 'basic',
    characters: [
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '春', pinyin: 'chūn', level: 'basic', words: ['春天', '春季'], meaning: '春' },
      { char: '夏', pinyin: 'xià', level: 'basic', words: ['夏天', '夏季'], meaning: '夏' },
      { char: '秋', pinyin: 'qiū', level: 'basic', words: ['秋天', '秋季'], meaning: '秋' },
      { char: '冬', pinyin: 'dōng', level: 'basic', words: ['冬天', '冬季'], meaning: '冬' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四个', '第四'], meaning: '四' },
      { char: '时', pinyin: 'shí', level: 'basic', words: ['时间', '时候'], meaning: '时' },
      { char: '运', pinyin: 'yùn', level: 'basic', words: ['运动', '运气'], meaning: '运行' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '穷', pinyin: 'qióng', level: 'basic', words: ['无穷', '贫穷'], meaning: '穷尽' },
      { char: '南', pinyin: 'nán', level: 'basic', words: ['南方', '江南'], meaning: '南' },
      { char: '北', pinyin: 'běi', level: 'basic', words: ['北方', '北面'], meaning: '北' },
      { char: '西', pinyin: 'xī', level: 'basic', words: ['西方', '西北'], meaning: '西' },
      { char: '东', pinyin: 'dōng', level: 'basic', words: ['东方', '东面'], meaning: '东' },
    ]
  },
  // 第十六段：四方
  {
    id: 'section-16',
    title: '曰南北',
    content: '曰南北，曰西东。此四方，应乎中。',
    pinyin: 'yuē nán běi, yuē xī dōng. cǐ sì fāng, yìng hū zhōng.',
    difficulty: 'basic',
    characters: [
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '南', pinyin: 'nán', level: 'basic', words: ['南方', '江南'], meaning: '南' },
      { char: '北', pinyin: 'běi', level: 'basic', words: ['北方', '北面'], meaning: '北' },
      { char: '西', pinyin: 'xī', level: 'basic', words: ['西方', '西北'], meaning: '西' },
      { char: '东', pinyin: 'dōng', level: 'basic', words: ['东方', '东面'], meaning: '东' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四个', '第四'], meaning: '四' },
      { char: '方', pinyin: 'fāng', level: 'basic', words: ['方法', '方向'], meaning: '方' },
      { char: '应', pinyin: 'yìng', level: 'basic', words: ['应该', '应用'], meaning: '对应' },
      { char: '乎', pinyin: 'hū', level: 'intermediate', words: ['似乎'], meaning: '于' },
      { char: '中', pinyin: 'zhōng', level: 'basic', words: ['中间', '中心'], meaning: '中央' },
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '水', pinyin: 'shuǐ', level: 'basic', words: ['河水', '喝水'], meaning: '水' },
      { char: '火', pinyin: 'huǒ', level: 'basic', words: ['火焰', '火柴'], meaning: '火' },
      { char: '木', pinyin: 'mù', level: 'basic', words: ['木头', '树木'], meaning: '木' },
    ]
  },
  // 第十七段：五行
  {
    id: 'section-17',
    title: '曰水火',
    content: '曰水火，木金土。此五行，本乎数。',
    pinyin: 'yuē shuǐ huǒ, mù jīn tǔ. cǐ wǔ háng, běn hū shù.',
    difficulty: 'basic',
    characters: [
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '水', pinyin: 'shuǐ', level: 'basic', words: ['河水', '喝水'], meaning: '水' },
      { char: '火', pinyin: 'huǒ', level: 'basic', words: ['火焰', '火柴'], meaning: '火' },
      { char: '木', pinyin: 'mù', level: 'basic', words: ['木头', '树木'], meaning: '木' },
      { char: '金', pinyin: 'jīn', level: 'basic', words: ['黄金', '金子'], meaning: '金' },
      { char: '土', pinyin: 'tǔ', level: 'basic', words: ['土地', '泥土'], meaning: '土' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '五', pinyin: 'wǔ', level: 'basic', words: ['五个', '第五'], meaning: '五' },
      { char: '行', pinyin: 'xíng', level: 'basic', words: ['行动', '行走'], meaning: '行' },
      { char: '本', pinyin: 'běn', level: 'basic', words: ['本来', '根本'], meaning: '本' },
      { char: '乎', pinyin: 'hū', level: 'intermediate', words: ['似乎'], meaning: '于' },
      { char: '数', pinyin: 'shù', level: 'basic', words: ['数字', '数学'], meaning: '数' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '干', pinyin: 'gān', level: 'basic', words: ['干净', '干活'], meaning: '干' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
    ]
  },
  // 第十八段：十干
  {
    id: 'section-18',
    title: '十干者',
    content: '十干者，甲至癸。十二支，子至亥。',
    pinyin: 'shí gān zhě, jiǎ zhì guǐ. shí èr zhī, zǐ zhì hài.',
    difficulty: 'advanced',
    characters: [
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '干', pinyin: 'gān', level: 'basic', words: ['干净', '干活'], meaning: '天干' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
      { char: '甲', pinyin: 'jiǎ', level: 'intermediate', words: ['甲子', '第一'], meaning: '甲' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '癸', pinyin: 'guǐ', level: 'advanced', words: ['癸丑'], meaning: '癸' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '二', pinyin: 'èr', level: 'basic', words: ['两个', '第二'], meaning: '二' },
      { char: '支', pinyin: 'zhī', level: 'basic', words: ['支持', '收支'], meaning: '地支' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '亥', pinyin: 'hài', level: 'advanced', words: ['亥时'], meaning: '亥' },
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '仁', pinyin: 'rén', level: 'basic', words: ['仁慈', '仁义'], meaning: '仁' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
    ]
  },
  // 第十九段：五常
  {
    id: 'section-19',
    title: '曰仁义',
    content: '曰仁义，礼智信。此五常，不容紊。',
    pinyin: 'yuē rén yì, lǐ zhì xìn. cǐ wǔ cháng, bù róng wěn.',
    difficulty: 'intermediate',
    characters: [
      { char: '曰', pinyin: 'yuē', level: 'basic', words: ['名曰'], meaning: '叫做' },
      { char: '仁', pinyin: 'rén', level: 'basic', words: ['仁慈', '仁义'], meaning: '仁' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼' },
      { char: '智', pinyin: 'zhì', level: 'basic', words: ['智慧', '智力'], meaning: '智' },
      { char: '信', pinyin: 'xìn', level: 'basic', words: ['相信', '信任'], meaning: '信' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '五', pinyin: 'wǔ', level: 'basic', words: ['五个', '第五'], meaning: '五' },
      { char: '常', pinyin: 'cháng', level: 'basic', words: ['经常', '平常'], meaning: '常' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '容', pinyin: 'róng', level: 'basic', words: ['容易', '内容'], meaning: '容许' },
      { char: '紊', pinyin: 'wěn', level: 'advanced', words: ['紊乱'], meaning: '乱' },
      { char: '稻', pinyin: 'dào', level: 'basic', words: ['水稻', '稻子'], meaning: '稻谷' },
      { char: '梁', pinyin: 'liáng', level: 'basic', words: ['高粱', '桥梁'], meaning: '高粱' },
      { char: '菽', pinyin: 'shū', level: 'advanced', words: ['菽水'], meaning: '豆类' },
    ]
  },
  // 第二十段：五谷
  {
    id: 'section-20',
    title: '稻梁菽',
    content: '稻梁菽，麦黍稷。此六谷，人所食。',
    pinyin: 'dào liáng shū, mài shǔ jì. cǐ liù gǔ, rén suǒ shí.',
    difficulty: 'intermediate',
    characters: [
      { char: '稻', pinyin: 'dào', level: 'basic', words: ['水稻', '稻子'], meaning: '稻谷' },
      { char: '梁', pinyin: 'liáng', level: 'basic', words: ['高粱', '桥梁'], meaning: '高粱' },
      { char: '菽', pinyin: 'shū', level: 'advanced', words: ['菽水'], meaning: '豆类' },
      { char: '麦', pinyin: 'mài', level: 'basic', words: ['小麦', '大麦'], meaning: '麦子' },
      { char: '黍', pinyin: 'shǔ', level: 'advanced', words: ['黍米'], meaning: '黄米' },
      { char: '稷', pinyin: 'jì', level: 'advanced', words: ['社稷'], meaning: '稷' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '六', pinyin: 'liù', level: 'basic', words: ['六个', '第六'], meaning: '六' },
      { char: '谷', pinyin: 'gǔ', level: 'basic', words: ['谷物', '五谷'], meaning: '谷物' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '所' },
      { char: '食', pinyin: 'shí', level: 'basic', words: ['食物', '饮食'], meaning: '吃' },
    ]
  },
  // 第二十一段：六畜
  {
    id: 'section-21',
    title: '马牛羊',
    content: '马牛羊，鸡犬豕。此六畜，人所饲。',
    pinyin: 'mǎ niú yáng, jī quǎn shǐ. cǐ liù chù, rén suǒ sì.',
    difficulty: 'basic',
    characters: [
      { char: '马', pinyin: 'mǎ', level: 'basic', words: ['马匹', '马上'], meaning: '马' },
      { char: '牛', pinyin: 'niú', level: 'basic', words: ['牛马', '黄牛'], meaning: '牛' },
      { char: '羊', pinyin: 'yáng', level: 'basic', words: ['山羊', '绵羊'], meaning: '羊' },
      { char: '鸡', pinyin: 'jī', level: 'basic', words: ['鸡鸭', '鸡蛋'], meaning: '鸡' },
      { char: '犬', pinyin: 'quǎn', level: 'basic', words: ['猎犬', '犬类'], meaning: '狗' },
      { char: '豕', pinyin: 'shǐ', level: 'advanced', words: ['豕突'], meaning: '猪' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '这' },
      { char: '六', pinyin: 'liù', level: 'basic', words: ['六个', '第六'], meaning: '六' },
      { char: '畜', pinyin: 'chù', level: 'intermediate', words: ['畜生'], meaning: '家畜' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '所' },
      { char: '饲', pinyin: 'sì', level: 'intermediate', words: ['饲养'], meaning: '饲养' },
    ]
  },
  // 第二十二段：七情
  {
    id: 'section-22',
    title: '曰喜怒',
    content: '曰喜怒，曰哀惧。爱恶欲，七情具。',
    pinyin: 'yuē xǐ nù, yuē āi jù. ài wù yù, qī qíng jù.',
    difficulty: 'basic',
    characters: [
      { char: '喜', pinyin: 'xǐ', level: 'basic', words: ['欢喜', '喜欢'], meaning: '高兴' },
      { char: '怒', pinyin: 'nù', level: 'basic', words: ['愤怒', '发怒'], meaning: '愤怒' },
      { char: '哀', pinyin: 'āi', level: 'basic', words: ['悲哀', '哀伤'], meaning: '悲哀' },
      { char: '惧', pinyin: 'jù', level: 'basic', words: ['恐惧', '惧怕'], meaning: '恐惧' },
      { char: '爱', pinyin: 'ài', level: 'basic', words: ['喜爱', '热爱'], meaning: '喜爱' },
      { char: '恶', pinyin: 'wù', level: 'basic', words: ['厌恶', '憎恶'], meaning: '憎恶' },
      { char: '欲', pinyin: 'yù', level: 'basic', words: ['欲望', '想要'], meaning: '欲望' },
      { char: '七', pinyin: 'qī', level: 'basic', words: ['七个', '第七'], meaning: '七' },
      { char: '情', pinyin: 'qíng', level: 'basic', words: ['感情', '心情'], meaning: '情感' },
      { char: '具', pinyin: 'jù', level: 'intermediate', words: ['具备', '工具'], meaning: '具备' },
      { char: '匏', pinyin: 'páo', level: 'advanced', words: ['匏瓜'], meaning: '葫芦' },
      { char: '土', pinyin: 'tǔ', level: 'basic', words: ['土地', '泥土'], meaning: '陶土' },
      { char: '革', pinyin: 'gé', level: 'basic', words: ['改革', '皮革'], meaning: '皮革' },
      { char: '木', pinyin: 'mù', level: 'basic', words: ['木头', '树木'], meaning: '木头' },
      { char: '石', pinyin: 'shí', level: 'basic', words: ['石头', '玉石'], meaning: '玉石' },
      { char: '金', pinyin: 'jīn', level: 'basic', words: ['黄金', '金子'], meaning: '金属' },
      { char: '丝', pinyin: 'sī', level: 'basic', words: ['丝绸', '丝线'], meaning: '丝' },
      { char: '竹', pinyin: 'zhú', level: 'basic', words: ['竹子', '竹林'], meaning: '竹子' },
    ]
  },
  // 第二十三段：八音
  {
    id: 'section-23',
    title: '匏土革',
    content: '匏土革，木石金。丝与竹，乃八音。',
    pinyin: 'páo tǔ gé, mù shí jīn. sī yǔ zhú, nǎi bā yīn.',
    difficulty: 'intermediate',
    characters: [
      { char: '匏', pinyin: 'páo', level: 'advanced', words: ['匏瓜'], meaning: '葫芦' },
      { char: '土', pinyin: 'tǔ', level: 'basic', words: ['土地', '泥土'], meaning: '陶土' },
      { char: '革', pinyin: 'gé', level: 'basic', words: ['改革', '皮革'], meaning: '皮革' },
      { char: '木', pinyin: 'mù', level: 'basic', words: ['木头', '树木'], meaning: '木头' },
      { char: '石', pinyin: 'shí', level: 'basic', words: ['石头', '玉石'], meaning: '玉石' },
      { char: '金', pinyin: 'jīn', level: 'basic', words: ['黄金', '金子'], meaning: '金属' },
      { char: '丝', pinyin: 'sī', level: 'basic', words: ['丝绸', '丝线'], meaning: '丝' },
      { char: '与', pinyin: 'yǔ', level: 'basic', words: ['与', '给予'], meaning: '和' },
      { char: '竹', pinyin: 'zhú', level: 'basic', words: ['竹子', '竹林'], meaning: '竹子' },
      { char: '乃', pinyin: 'nǎi', level: 'intermediate', words: ['乃是'], meaning: '是' },
      { char: '八', pinyin: 'bā', level: 'basic', words: ['八个', '第八'], meaning: '八' },
      { char: '音', pinyin: 'yīn', level: 'basic', words: ['声音', '音乐'], meaning: '音' },
      { char: '高', pinyin: 'gāo', level: 'basic', words: ['高大', '高级'], meaning: '高' },
      { char: '曾', pinyin: 'zēng', level: 'intermediate', words: ['曾经', '曾祖'], meaning: '曾祖' },
      { char: '祖', pinyin: 'zǔ', level: 'basic', words: ['祖先', '祖父'], meaning: '祖父' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父亲' },
      { char: '身', pinyin: 'shēn', level: 'basic', words: ['身体', '自身'], meaning: '自身' },
      { char: '而', pinyin: 'ér', level: 'basic', words: ['而且', '然而'], meaning: '而' },
    ]
  },
  // 第二十四段：九族
  {
    id: 'section-24',
    title: '高曾祖',
    content: '高曾祖，父而身。身而子，子而孙。',
    pinyin: 'gāo zēng zǔ, fù ér shēn. shēn ér zǐ, zǐ ér sūn.',
    difficulty: 'basic',
    characters: [
      { char: '高', pinyin: 'gāo', level: 'basic', words: ['高大', '高级'], meaning: '高祖' },
      { char: '曾', pinyin: 'zēng', level: 'intermediate', words: ['曾经', '曾祖'], meaning: '曾祖' },
      { char: '祖', pinyin: 'zǔ', level: 'basic', words: ['祖先', '祖父'], meaning: '祖父' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父亲' },
      { char: '而', pinyin: 'ér', level: 'basic', words: ['而且', '然而'], meaning: '而' },
      { char: '身', pinyin: 'shēn', level: 'basic', words: ['身体', '自身'], meaning: '自身' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
      { char: '孙', pinyin: 'sūn', level: 'basic', words: ['孙子', '子孙'], meaning: '孙子' },
      { char: '自', pinyin: 'zì', level: 'basic', words: ['自己', '自然'], meaning: '自己' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
      { char: '孙', pinyin: 'sūn', level: 'basic', words: ['孙子', '子孙'], meaning: '孙子' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '玄', pinyin: 'xuán', level: 'intermediate', words: ['玄孙'], meaning: '玄孙' },
      { char: '曾', pinyin: 'zēng', level: 'intermediate', words: ['曾经', '曾孙'], meaning: '曾孙' },
    ]
  },
  // 第二十五段：九族续
  {
    id: 'section-25',
    title: '自子孙',
    content: '自子孙，至玄曾。乃九族，人之伦。',
    pinyin: 'zì zǐ sūn, zhì xuán zēng. nǎi jiǔ zú, rén zhī lún.',
    difficulty: 'intermediate',
    characters: [
      { char: '自', pinyin: 'zì', level: 'basic', words: ['自己', '自然'], meaning: '从' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '儿子' },
      { char: '孙', pinyin: 'sūn', level: 'basic', words: ['孙子', '子孙'], meaning: '孙子' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '玄', pinyin: 'xuán', level: 'intermediate', words: ['玄孙'], meaning: '玄孙' },
      { char: '曾', pinyin: 'zēng', level: 'intermediate', words: ['曾经', '曾孙'], meaning: '曾孙' },
      { char: '乃', pinyin: 'nǎi', level: 'intermediate', words: ['乃是'], meaning: '是' },
      { char: '九', pinyin: 'jiǔ', level: 'basic', words: ['九个', '第九'], meaning: '九' },
      { char: '族', pinyin: 'zú', level: 'basic', words: ['家族', '民族'], meaning: '族' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '的' },
      { char: '伦', pinyin: 'lún', level: 'intermediate', words: ['伦理'], meaning: '伦理' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父子' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '夫', pinyin: 'fū', level: 'basic', words: ['丈夫', '农夫'], meaning: '夫妇' },
      { char: '妇', pinyin: 'fù', level: 'basic', words: ['妇女', '夫妇'], meaning: '妇' },
      { char: '随', pinyin: 'suí', level: 'basic', words: ['跟随', '随便'], meaning: '随从' },
    ]
  },
  // 第二十六段：父子夫妇
  {
    id: 'section-26',
    title: '父子恩',
    content: '父子恩，夫妇从。兄则友，弟则恭。',
    pinyin: 'fù zǐ ēn, fū fù cóng. xiōng zé yǒu, dì zé gōng.',
    difficulty: 'basic',
    characters: [
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '恩', pinyin: 'ēn', level: 'basic', words: ['恩情', '恩惠'], meaning: '恩' },
      { char: '夫', pinyin: 'fū', level: 'basic', words: ['丈夫', '农夫'], meaning: '夫' },
      { char: '妇', pinyin: 'fù', level: 'basic', words: ['妇女', '夫妇'], meaning: '妇' },
      { char: '从', pinyin: 'cóng', level: 'basic', words: ['跟随', '服从'], meaning: '随从' },
      { char: '兄', pinyin: 'xiōng', level: 'basic', words: ['兄弟', '兄长'], meaning: '兄' },
      { char: '则', pinyin: 'zé', level: 'basic', words: ['则', '否则'], meaning: '则' },
      { char: '友', pinyin: 'yǒu', level: 'basic', words: ['朋友', '友好'], meaning: '友爱' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '弟' },
      { char: '恭', pinyin: 'gōng', level: 'basic', words: ['恭敬', '恭贺'], meaning: '恭敬' },
      { char: '长', pinyin: 'zhǎng', level: 'basic', words: ['长辈', '长大'], meaning: '长辈' },
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '幼辈' },
      { char: '序', pinyin: 'xù', level: 'basic', words: ['顺序', '秩序'], meaning: '秩序' },
      { char: '友', pinyin: 'yǒu', level: 'basic', words: ['朋友', '友好'], meaning: '友爱' },
      { char: '朋', pinyin: 'péng', level: 'basic', words: ['朋友', '亲朋'], meaning: '朋友' },
    ]
  },
  // 第二十七段：长幼有序
  {
    id: 'section-27',
    title: '长幼序',
    content: '长幼序，友与朋。君则敬，臣则忠。',
    pinyin: 'zhǎng yòu xù, yǒu yǔ péng. jūn zé jìng, chén zé zhōng.',
    difficulty: 'basic',
    characters: [
      { char: '长', pinyin: 'zhǎng', level: 'basic', words: ['长辈', '长大'], meaning: '长' },
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '幼' },
      { char: '序', pinyin: 'xù', level: 'basic', words: ['顺序', '秩序'], meaning: '次序' },
      { char: '友', pinyin: 'yǒu', level: 'basic', words: ['朋友', '友好'], meaning: '朋友' },
      { char: '与', pinyin: 'yǔ', level: 'basic', words: ['与', '给予'], meaning: '与' },
      { char: '朋', pinyin: 'péng', level: 'basic', words: ['朋友', '亲朋'], meaning: '朋友' },
      { char: '君', pinyin: 'jūn', level: 'basic', words: ['君子', '君主'], meaning: '君主' },
      { char: '则', pinyin: 'zé', level: 'basic', words: ['则', '否则'], meaning: '则' },
      { char: '敬', pinyin: 'jìng', level: 'basic', words: ['尊敬', '敬礼'], meaning: '敬重' },
      { char: '臣', pinyin: 'chén', level: 'basic', words: ['大臣', '臣子'], meaning: '臣子' },
      { char: '忠', pinyin: 'zhōng', level: 'basic', words: ['忠诚', '忠心'], meaning: '忠诚' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '此' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '所' },
      { char: '同', pinyin: 'tóng', level: 'basic', words: ['相同', '共同'], meaning: '同' },
    ]
  },
  // 第二十八段：十义
  {
    id: 'section-28',
    title: '此十义',
    content: '此十义，人所同。凡训蒙，须讲究。',
    pinyin: 'cǐ shí yì, rén suǒ tóng. fán xùn méng, xū jiǎng jiū.',
    difficulty: 'intermediate',
    characters: [
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '此' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '所', pinyin: 'suǒ', level: 'basic', words: ['所以', '所处'], meaning: '所' },
      { char: '同', pinyin: 'tóng', level: 'basic', words: ['相同', '共同'], meaning: '同' },
      { char: '凡', pinyin: 'fán', level: 'basic', words: ['平凡', '凡是'], meaning: '凡是' },
      { char: '训', pinyin: 'xùn', level: 'intermediate', words: ['教训', '训导'], meaning: '教导' },
      { char: '蒙', pinyin: 'méng', level: 'intermediate', words: ['启蒙', '蒙学'], meaning: '儿童' },
      { char: '须', pinyin: 'xū', level: 'basic', words: ['必须', '须要'], meaning: '必须' },
      { char: '讲', pinyin: 'jiǎng', level: 'basic', words: ['讲话', '讲解'], meaning: '讲解' },
      { char: '究', pinyin: 'jiū', level: 'intermediate', words: ['研究', '追究'], meaning: '研究' },
      { char: '详', pinyin: 'xiáng', level: 'basic', words: ['详细', '详情'], meaning: '详细' },
      { char: '训', pinyin: 'xùn', level: 'intermediate', words: ['教训', '训导'], meaning: '讲解' },
      { char: '明', pinyin: 'míng', level: 'basic', words: ['明白', '清楚'], meaning: '明白' },
      { char: '句', pinyin: 'jù', level: 'basic', words: ['句子', '句号'], meaning: '句子' },
      { char: '读', pinyin: 'dú', level: 'basic', words: ['读书', '阅读'], meaning: '读' },
      { char: '史', pinyin: 'shǐ', level: 'basic', words: ['历史', '史书'], meaning: '历史' },
    ]
  },
  // 第二十九段：训诂
  {
    id: 'section-29',
    title: '详训诂',
    content: '详训诂，明句读。为学者，必有初。',
    pinyin: 'xiáng xùn gǔ, míng jù dòu. wéi xué zhě, bì yǒu chū.',
    difficulty: 'intermediate',
    characters: [
      { char: '详', pinyin: 'xiáng', level: 'basic', words: ['详细', '详情'], meaning: '详细' },
      { char: '训', pinyin: 'xùn', level: 'intermediate', words: ['教训', '训导'], meaning: '训释' },
      { char: '诂', pinyin: 'gǔ', level: 'advanced', words: ['训诂'], meaning: '古义' },
      { char: '明', pinyin: 'míng', level: 'basic', words: ['明白', '清楚'], meaning: '明白' },
      { char: '句', pinyin: 'jù', level: 'basic', words: ['句子', '句号'], meaning: '句子' },
      { char: '读', pinyin: 'dòu', level: 'advanced', words: ['句读'], meaning: '停顿' },
      { char: '为', pinyin: 'wéi', level: 'basic', words: ['作为', '行为'], meaning: '做' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '的人' },
      { char: '必', pinyin: 'bì', level: 'basic', words: ['必须', '必然'], meaning: '必须' },
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '初', pinyin: 'chū', level: 'basic', words: ['初一', '初次'], meaning: '开始' },
      { char: '小', pinyin: 'xiǎo', level: 'basic', words: ['小学', '小孩'], meaning: '小学' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学习' },
      { char: '终', pinyin: 'zhōng', level: 'basic', words: ['终点', '最终'], meaning: '结束' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四个', '第四'], meaning: '四' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '书籍' },
    ]
  },
  // 第三十段：小学
  {
    id: 'section-30',
    title: '小学终',
    content: '小学终，至四书。论语者，二十篇。',
    pinyin: 'xiǎo xué zhōng, zhì sì shū. lún yǔ zhě, èr shí piān.',
    difficulty: 'intermediate',
    characters: [
      { char: '小', pinyin: 'xiǎo', level: 'basic', words: ['小学', '小孩'], meaning: '小' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '终', pinyin: 'zhōng', level: 'basic', words: ['终点', '最终'], meaning: '结束' },
      { char: '至', pinyin: 'zhì', level: 'basic', words: ['至此', '甚至'], meaning: '到' },
      { char: '四', pinyin: 'sì', level: 'basic', words: ['四个', '第四'], meaning: '四' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '书' },
      { char: '论', pinyin: 'lún', level: 'intermediate', words: ['论语', '讨论'], meaning: '论语' },
      { char: '语', pinyin: 'yǔ', level: 'basic', words: ['语言', '语文'], meaning: '语' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
      { char: '二', pinyin: 'èr', level: 'basic', words: ['两个', '第二'], meaning: '二' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '篇', pinyin: 'piān', level: 'basic', words: ['篇章', '文章'], meaning: '篇' },
      { char: '群', pinyin: 'qún', level: 'basic', words: ['人群', '群众'], meaning: '弟子' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '弟子' },
      { char: '记', pinyin: 'jì', level: 'basic', words: ['记录', '记忆'], meaning: '记' },
      { char: '善', pinyin: 'shàn', level: 'basic', words: ['善良', '友善'], meaning: '善言' },
    ]
  },
  // 第三十一段：论语
  {
    id: 'section-31',
    title: '群弟子',
    content: '群弟子，记善言。孟子者，七篇止。',
    pinyin: 'qún dì zǐ, jì shàn yán. mèng zǐ zhě, qī piān zhǐ.',
    difficulty: 'intermediate',
    characters: [
      { char: '群', pinyin: 'qún', level: 'basic', words: ['人群', '群众'], meaning: '弟子' },
      { char: '弟', pinyin: 'dì', level: 'basic', words: ['弟弟', '兄弟'], meaning: '弟子' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '记', pinyin: 'jì', level: 'basic', words: ['记录', '记忆'], meaning: '记' },
      { char: '善', pinyin: 'shàn', level: 'basic', words: ['善良', '友善'], meaning: '善' },
      { char: '言', pinyin: 'yán', level: 'basic', words: ['语言', '说话'], meaning: '言' },
      { char: '孟', pinyin: 'mèng', level: 'intermediate', words: ['孟子', '孟母'], meaning: '孟子' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '者', pinyin: 'zhě', level: 'basic', words: ['作者', '或者'], meaning: '指' },
      { char: '七', pinyin: 'qī', level: 'basic', words: ['七个', '第七'], meaning: '七' },
      { char: '篇', pinyin: 'piān', level: 'basic', words: ['篇章', '文章'], meaning: '篇' },
      { char: '止', pinyin: 'zhǐ', level: 'basic', words: ['停止', '终止'], meaning: '止' },
      { char: '讲', pinyin: 'jiǎng', level: 'basic', words: ['讲话', '讲解'], meaning: '讲' },
      { char: '仁', pinyin: 'rén', level: 'basic', words: ['仁慈', '仁义'], meaning: '仁' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼' },
      { char: '智', pinyin: 'zhì', level: 'basic', words: ['智慧', '智力'], meaning: '智' },
    ]
  },
  // 第三十二段：孟子
  {
    id: 'section-32',
    title: '讲仁义',
    content: '讲仁义，礼智信。此六经，始可读。',
    pinyin: 'jiǎng rén yì, lǐ zhì xìn. cǐ liù jīng, shǐ kě dú.',
    difficulty: 'intermediate',
    characters: [
      { char: '讲', pinyin: 'jiǎng', level: 'basic', words: ['讲话', '讲解'], meaning: '讲' },
      { char: '仁', pinyin: 'rén', level: 'basic', words: ['仁慈', '仁义'], meaning: '仁' },
      { char: '义', pinyin: 'yì', level: 'basic', words: ['正义', '义气'], meaning: '义' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼' },
      { char: '智', pinyin: 'zhì', level: 'basic', words: ['智慧', '智力'], meaning: '智' },
      { char: '信', pinyin: 'xìn', level: 'basic', words: ['相信', '信任'], meaning: '信' },
      { char: '此', pinyin: 'cǐ', level: 'basic', words: ['此时', '此地'], meaning: '此' },
      { char: '六', pinyin: 'liù', level: 'basic', words: ['六个', '第六'], meaning: '六' },
      { char: '经', pinyin: 'jīng', level: 'basic', words: ['经书', '经典'], meaning: '经' },
      { char: '始', pinyin: 'shǐ', level: 'basic', words: ['开始', '起始'], meaning: '开始' },
      { char: '可', pinyin: 'kě', level: 'basic', words: ['可以', '可能'], meaning: '可' },
      { char: '读', pinyin: 'dú', level: 'basic', words: ['读书', '阅读'], meaning: '读' },
      { char: '诗', pinyin: 'shī', level: 'basic', words: ['诗歌', '诗经'], meaning: '诗' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '书' },
      { char: '易', pinyin: 'yì', level: 'basic', words: ['容易', '简易'], meaning: '易' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼' },
      { char: '春', pinyin: 'chūn', level: 'basic', words: ['春天', '春季'], meaning: '春秋' },
    ]
  },
  // 第三十三段：六经
  {
    id: 'section-33',
    title: '诗书易',
    content: '诗书易，礼春秋。号六经，当讲求。',
    pinyin: 'shī shū yì, lǐ chūn qiū. hào liù jīng, dāng jiǎng qiú.',
    difficulty: 'intermediate',
    characters: [
      { char: '诗', pinyin: 'shī', level: 'basic', words: ['诗歌', '诗经'], meaning: '诗经' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '尚书' },
      { char: '易', pinyin: 'yì', level: 'basic', words: ['容易', '简易'], meaning: '周易' },
      { char: '礼', pinyin: 'lǐ', level: 'basic', words: ['礼貌', '礼仪'], meaning: '礼记' },
      { char: '春', pinyin: 'chūn', level: 'basic', words: ['春天', '春季'], meaning: '春秋' },
      { char: '秋', pinyin: 'qiū', level: 'basic', words: ['秋天', '秋季'], meaning: '春秋' },
      { char: '号', pinyin: 'hào', level: 'basic', words: ['号令', '口号'], meaning: '号称' },
      { char: '六', pinyin: 'liù', level: 'basic', words: ['六个', '第六'], meaning: '六' },
      { char: '经', pinyin: 'jīng', level: 'basic', words: ['经书', '经典'], meaning: '经' },
      { char: '当', pinyin: 'dāng', level: 'basic', words: ['应当', '当时'], meaning: '应当' },
      { char: '讲', pinyin: 'jiǎng', level: 'basic', words: ['讲话', '讲解'], meaning: '讲' },
      { char: '求', pinyin: 'qiú', level: 'basic', words: ['追求', '要求'], meaning: '求' },
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '连', pinyin: 'lián', level: 'basic', words: ['连线', '连接'], meaning: '连山' },
      { char: '山', pinyin: 'shān', level: 'basic', words: ['高山', '山水'], meaning: '山' },
      { char: '归', pinyin: 'guī', level: 'basic', words: ['回归', '归家'], meaning: '归藏' },
      { char: '藏', pinyin: 'zàng', level: 'basic', words: ['躲藏', '收藏'], meaning: '藏' },
    ]
  },
  // 第三十四段：三易
  {
    id: 'section-34',
    title: '有连山',
    content: '有连山，有归藏。有周易，三易详。',
    pinyin: 'yǒu lián shān, yǒu guī cáng. yǒu zhōu yì, sān yì xiáng.',
    difficulty: 'advanced',
    characters: [
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '连', pinyin: 'lián', level: 'basic', words: ['连线', '连接'], meaning: '连' },
      { char: '山', pinyin: 'shān', level: 'basic', words: ['高山', '山水'], meaning: '山' },
      { char: '归', pinyin: 'guī', level: 'basic', words: ['回归', '归家'], meaning: '归' },
      { char: '藏', pinyin: 'zàng', level: 'basic', words: ['躲藏', '收藏'], meaning: '藏' },
      { char: '周', pinyin: 'zhōu', level: 'basic', words: ['周围', '四周'], meaning: '周' },
      { char: '易', pinyin: 'yì', level: 'basic', words: ['容易', '简易'], meaning: '易' },
      { char: '三', pinyin: 'sān', level: 'basic', words: ['三个', '第三'], meaning: '三' },
      { char: '易', pinyin: 'yì', level: 'basic', words: ['容易', '简易'], meaning: '易' },
      { char: '详', pinyin: 'xiáng', level: 'basic', words: ['详细', '详情'], meaning: '详' },
      { char: '典', pinyin: 'diǎn', level: 'basic', words: ['字典', '经典'], meaning: '典' },
      { char: '籍', pinyin: 'jí', level: 'basic', words: ['书籍', '典籍'], meaning: '籍' },
      { char: '甚', pinyin: 'shèn', level: 'intermediate', words: ['甚至', '甚好'], meaning: '很' },
      { char: '多', pinyin: 'duō', level: 'basic', words: ['很多', '多数'], meaning: '多' },
    ]
  },
  // 第三十五段：典籍
  {
    id: 'section-35',
    title: '有典籍',
    content: '有典籍，有训诂。甚多矣，难尽述。',
    pinyin: 'yǒu diǎn jí, yǒu xùn gǔ. shèn duō yǐ, nán jìn shù.',
    difficulty: 'advanced',
    characters: [
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '典', pinyin: 'diǎn', level: 'basic', words: ['字典', '经典'], meaning: '典' },
      { char: '籍', pinyin: 'jí', level: 'basic', words: ['书籍', '典籍'], meaning: '籍' },
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '训', pinyin: 'xùn', level: 'intermediate', words: ['教训', '训导'], meaning: '训' },
      { char: '诂', pinyin: 'gǔ', level: 'advanced', words: ['训诂'], meaning: '诂' },
      { char: '甚', pinyin: 'shèn', level: 'intermediate', words: ['甚至', '甚好'], meaning: '很' },
      { char: '多', pinyin: 'duō', level: 'basic', words: ['很多', '多数'], meaning: '多' },
      { char: '矣', pinyin: 'yǐ', level: 'intermediate', words: ['而已'], meaning: '了' },
      { char: '难', pinyin: 'nán', level: 'basic', words: ['困难', '艰难'], meaning: '难' },
      { char: '尽', pinyin: 'jìn', level: 'basic', words: ['尽力', '尽头'], meaning: '尽' },
      { char: '述', pinyin: 'shù', level: 'intermediate', words: ['叙述', '论述'], meaning: '述' },
    ]
  },
  // 第三十六段：学习
  {
    id: 'section-36',
    title: '口而诵',
    content: '口而诵，心而惟。朝于斯，夕于斯。',
    pinyin: 'kǒu ér sòng, xīn ér wéi. zhāo yú sī, xī yú sī.',
    difficulty: 'basic',
    characters: [
      { char: '口', pinyin: 'kǒu', level: 'basic', words: ['口头', '口才'], meaning: '口' },
      { char: '而', pinyin: 'ér', level: 'basic', words: ['而且', '然而'], meaning: '而' },
      { char: '诵', pinyin: 'sòng', level: 'intermediate', words: ['朗诵', '背诵'], meaning: '诵' },
      { char: '心', pinyin: 'xīn', level: 'basic', words: ['心灵', '心情'], meaning: '心' },
      { char: '惟', pinyin: 'wéi', level: 'intermediate', words: ['惟有', '思惟'], meaning: '思' },
      { char: '朝', pinyin: 'zhāo', level: 'basic', words: ['早晨', '朝阳'], meaning: '早晨' },
      { char: '于', pinyin: 'yú', level: 'basic', words: ['关于', '由于'], meaning: '在' },
      { char: '斯', pinyin: 'sī', level: 'intermediate', words: ['斯人'], meaning: '此' },
      { char: '夕', pinyin: 'xī', level: 'basic', words: ['夕阳', '前夕'], meaning: '傍晚' },
      { char: '昔', pinyin: 'xī', level: 'intermediate', words: ['昔日', '往昔'], meaning: '从前' },
      { char: '仲', pinyin: 'zhòng', level: 'intermediate', words: ['仲尼'], meaning: '孔子' },
      { char: '尼', pinyin: 'ní', level: 'basic', words: ['尼姑', '尼龙'], meaning: '字' },
      { char: '项', pinyin: 'xiàng', level: 'basic', words: ['项目', '项圈'], meaning: '项' },
      { char: '橐', pinyin: 'tuó', level: 'advanced', words: ['囊橐'], meaning: '口袋' },
      { char: '古', pinyin: 'gǔ', level: 'basic', words: ['古代', '古老'], meaning: '古代' },
      { char: '圣', pinyin: 'shèng', level: 'basic', words: ['神圣', '圣人'], meaning: '圣' },
      { char: '贤', pinyin: 'xián', level: 'basic', words: ['贤惠', '圣贤'], meaning: '贤' },
    ]
  },
  // 第三十七段：孔子
  {
    id: 'section-37',
    title: '昔仲尼',
    content: '昔仲尼，师项橐。古圣贤，尚勤学。',
    pinyin: 'xī zhòng ní, shī xiàng tuó. gǔ shèng xián, shàng qín xué.',
    difficulty: 'advanced',
    characters: [
      { char: '昔', pinyin: 'xī', level: 'intermediate', words: ['昔日', '往昔'], meaning: '从前' },
      { char: '仲', pinyin: 'zhòng', level: 'intermediate', words: ['仲尼'], meaning: '孔子' },
      { char: '尼', pinyin: 'ní', level: 'basic', words: ['尼姑', '尼龙'], meaning: '孔子' },
      { char: '师', pinyin: 'shī', level: 'basic', words: ['老师', '师父'], meaning: '师' },
      { char: '项', pinyin: 'xiàng', level: 'basic', words: ['项目', '项圈'], meaning: '项' },
      { char: '橐', pinyin: 'tuó', level: 'advanced', words: ['囊橐'], meaning: '项橐' },
      { char: '古', pinyin: 'gǔ', level: 'basic', words: ['古代', '古老'], meaning: '古代' },
      { char: '圣', pinyin: 'shèng', level: 'basic', words: ['神圣', '圣人'], meaning: '圣' },
      { char: '贤', pinyin: 'xián', level: 'basic', words: ['贤惠', '圣贤'], meaning: '贤' },
      { char: '尚', pinyin: 'shàng', level: 'basic', words: ['高尚', '崇尚'], meaning: '尚' },
      { char: '勤', pinyin: 'qín', level: 'basic', words: ['勤劳', '勤奋'], meaning: '勤' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
    ]
  },
  // 第三十八段：赵中令
  {
    id: 'section-38',
    title: '赵中令',
    content: '赵中令，读鲁论。彼既仕，学且勤。',
    pinyin: 'zhào zhōng lìng, dú lǔ lùn. bǐ jì shì, xué qiě qín.',
    difficulty: 'intermediate',
    characters: [
      { char: '赵', pinyin: 'zhào', level: 'basic', words: ['赵国', '老赵'], meaning: '赵普' },
      { char: '中', pinyin: 'zhōng', level: 'basic', words: ['中间', '中心'], meaning: '中令' },
      { char: '令', pinyin: 'lìng', level: 'basic', words: ['命令', '令'], meaning: '令' },
      { char: '读', pinyin: 'dú', level: 'basic', words: ['读书', '阅读'], meaning: '读' },
      { char: '鲁', pinyin: 'lǔ', level: 'basic', words: ['鲁国', '山东'], meaning: '鲁' },
      { char: '论', pinyin: 'lùn', level: 'intermediate', words: ['论语', '讨论'], meaning: '论语' },
      { char: '彼', pinyin: 'bǐ', level: 'intermediate', words: ['彼此', '彼岸'], meaning: '他' },
      { char: '既', pinyin: 'jì', level: 'intermediate', words: ['既然', '既而'], meaning: '已经' },
      { char: '仕', pinyin: 'shì', level: 'intermediate', words: ['仕途', '出仕'], meaning: '做官' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '且', pinyin: 'qiě', level: 'basic', words: ['并且', '暂且'], meaning: '而且' },
      { char: '勤', pinyin: 'qín', level: 'basic', words: ['勤劳', '勤奋'], meaning: '勤' },
    ]
  },
  // 第三十九段：披蒲编
  {
    id: 'section-39',
    title: '披蒲编',
    content: '披蒲编，削竹简。彼无书，且知勉。',
    pinyin: 'pī pú biān, xuē zhú jiǎn. bǐ wú shū, qiě zhī miǎn.',
    difficulty: 'intermediate',
    characters: [
      { char: '披', pinyin: 'pī', level: 'basic', words: ['披肩', '披风'], meaning: '披' },
      { char: '蒲', pinyin: 'pú', level: 'basic', words: ['蒲草', '蒲扇'], meaning: '蒲草' },
      { char: '编', pinyin: 'biān', level: 'basic', words: ['编辑', '编写'], meaning: '编' },
      { char: '削', pinyin: 'xuē', level: 'basic', words: ['削皮', '剥削'], meaning: '削' },
      { char: '竹', pinyin: 'zhú', level: 'basic', words: ['竹子', '竹林'], meaning: '竹' },
      { char: '简', pinyin: 'jiǎn', level: 'basic', words: ['简单', '简略'], meaning: '简' },
      { char: '彼', pinyin: 'bǐ', level: 'intermediate', words: ['彼此', '彼岸'], meaning: '他' },
      { char: '无', pinyin: 'wú', level: 'basic', words: ['无', '没有'], meaning: '无' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '书' },
      { char: '且', pinyin: 'qiě', level: 'basic', words: ['并且', '暂且'], meaning: '且' },
      { char: '知', pinyin: 'zhī', level: 'basic', words: ['知道', '知识'], meaning: '知' },
      { char: '勉', pinyin: 'miǎn', level: 'intermediate', words: ['勉励', '勤勉'], meaning: '勉' },
    ]
  },
  // 第四十段：头悬梁
  {
    id: 'section-40',
    title: '头悬梁',
    content: '头悬梁，锥刺股。彼不教，自勤苦。',
    pinyin: 'tóu xuán liáng, zhuī cì gǔ. bǐ bù jiào, zì qín kǔ.',
    difficulty: 'intermediate',
    characters: [
      { char: '头', pinyin: 'tóu', level: 'basic', words: ['头发', '头疼'], meaning: '头' },
      { char: '悬', pinyin: 'xuán', level: 'intermediate', words: ['悬挂', '悬空'], meaning: '悬' },
      { char: '梁', pinyin: 'liáng', level: 'basic', words: ['梁上', '桥梁'], meaning: '梁' },
      { char: '锥', pinyin: 'zhuī', level: 'intermediate', words: ['圆锥', '锥子'], meaning: '锥' },
      { char: '刺', pinyin: 'cì', level: 'basic', words: ['刺刀', '刺激'], meaning: '刺' },
      { char: '股', pinyin: 'gǔ', level: 'basic', words: ['屁股', '大腿'], meaning: '大腿' },
      { char: '彼', pinyin: 'bǐ', level: 'intermediate', words: ['彼此', '彼岸'], meaning: '他' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教' },
      { char: '自', pinyin: 'zì', level: 'basic', words: ['自己', '自然'], meaning: '自己' },
      { char: '勤', pinyin: 'qín', level: 'basic', words: ['勤劳', '勤奋'], meaning: '勤' },
      { char: '苦', pinyin: 'kǔ', level: 'basic', words: ['辛苦', '痛苦'], meaning: '苦' },
    ]
  },
  // 第四十一段：如囊萤
  {
    id: 'section-41',
    title: '如囊萤',
    content: '如囊萤，如映雪。家虽贫，学不辍。',
    pinyin: 'rú náng yíng, rú yìng xuě. jiā suī pín, xué bù chuò.',
    difficulty: 'intermediate',
    characters: [
      { char: '如', pinyin: 'rú', level: 'basic', words: ['如果', '如'], meaning: '如' },
      { char: '囊', pinyin: 'náng', level: 'intermediate', words: ['锦囊', '书包'], meaning: '囊' },
      { char: '萤', pinyin: 'yíng', level: 'basic', words: ['萤火虫', '萤光'], meaning: '萤火虫' },
      { char: '映', pinyin: 'yìng', level: 'basic', words: ['反映', '照耀'], meaning: '映照' },
      { char: '雪', pinyin: 'xuě', level: 'basic', words: ['雪白', '下雪'], meaning: '雪' },
      { char: '家', pinyin: 'jiā', level: 'basic', words: ['家庭', '家人'], meaning: '家' },
      { char: '虽', pinyin: 'suī', level: 'intermediate', words: ['虽然', '虽说'], meaning: '虽然' },
      { char: '贫', pinyin: 'pín', level: 'basic', words: ['贫穷', '贫苦'], meaning: '贫穷' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '辍', pinyin: 'chuò', level: 'advanced', words: ['辍学'], meaning: '停止' },
    ]
  },
  // 第四十二段：如负薪
  {
    id: 'section-42',
    title: '如负薪',
    content: '如负薪，如挂角。身虽劳，犹苦卓。',
    pinyin: 'rú fù xīn, rú guà jiǎo. shēn suī láo, yóu kǔ zhuó.',
    difficulty: 'intermediate',
    characters: [
      { char: '如', pinyin: 'rú', level: 'basic', words: ['如果', '如'], meaning: '如' },
      { char: '负', pinyin: 'fù', level: 'basic', words: ['负担', '胜负'], meaning: '背' },
      { char: '薪', pinyin: 'xīn', level: 'basic', words: ['薪水', '薪柴'], meaning: '柴' },
      { char: '挂', pinyin: 'guà', level: 'basic', words: ['挂起', '悬挂'], meaning: '挂' },
      { char: '角', pinyin: 'jiǎo', level: 'basic', words: ['角落', '角度'], meaning: '角' },
      { char: '身', pinyin: 'shēn', level: 'basic', words: ['身体', '自身'], meaning: '身' },
      { char: '虽', pinyin: 'suī', level: 'intermediate', words: ['虽然', '虽说'], meaning: '虽然' },
      { char: '劳', pinyin: 'láo', level: 'basic', words: ['劳动', '劳累'], meaning: '劳' },
      { char: '犹', pinyin: 'yóu', level: 'intermediate', words: ['犹如', '犹豫'], meaning: '仍然' },
      { char: '苦', pinyin: 'kǔ', level: 'basic', words: ['辛苦', '痛苦'], meaning: '苦' },
      { char: '卓', pinyin: 'zhuó', level: 'intermediate', words: ['卓越', '卓著'], meaning: '卓越' },
    ]
  },
  // 第四十三段：苏老泉
  {
    id: 'section-43',
    title: '苏老泉',
    content: '苏老泉，二十七。始发愤，读书籍。',
    pinyin: 'sū lǎo quán, èr shí qī. shǐ fā fèn, dú shū jí.',
    difficulty: 'intermediate',
    characters: [
      { char: '苏', pinyin: 'sū', level: 'basic', words: ['苏州', '苏醒'], meaning: '苏洵' },
      { char: '老', pinyin: 'lǎo', level: 'basic', words: ['老人', '年老'], meaning: '老' },
      { char: '泉', pinyin: 'quán', level: 'basic', words: ['泉水', '源泉'], meaning: '泉' },
      { char: '二', pinyin: 'èr', level: 'basic', words: ['两个', '第二'], meaning: '二' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '七', pinyin: 'qī', level: 'basic', words: ['七个', '第七'], meaning: '七' },
      { char: '始', pinyin: 'shǐ', level: 'basic', words: ['开始', '起始'], meaning: '开始' },
      { char: '发', pinyin: 'fā', level: 'basic', words: ['出发', '出发'], meaning: '发' },
      { char: '愤', pinyin: 'fèn', level: 'basic', words: ['气愤', '发愤'], meaning: '愤' },
      { char: '读', pinyin: 'dú', level: 'basic', words: ['读书', '阅读'], meaning: '读' },
      { char: '书', pinyin: 'shū', level: 'basic', words: ['书本', '书籍'], meaning: '书' },
      { char: '籍', pinyin: 'jí', level: 'basic', words: ['书籍', '典籍'], meaning: '籍' },
    ]
  },
  // 第四十四段：既老
  {
    id: 'section-44',
    title: '既老矣',
    content: '既老矣，悔迟矣。尔小生，宜早思。',
    pinyin: 'jì lǎo yǐ, huǐ chí yǐ. ěr xiǎo shēng, yí zǎo sī.',
    difficulty: 'basic',
    characters: [
      { char: '既', pinyin: 'jì', level: 'intermediate', words: ['既然', '既而'], meaning: '已经' },
      { char: '老', pinyin: 'lǎo', level: 'basic', words: ['老人', '年老'], meaning: '老' },
      { char: '矣', pinyin: 'yǐ', level: 'intermediate', words: ['而已'], meaning: '了' },
      { char: '悔', pinyin: 'huǐ', level: 'basic', words: ['后悔', '悔恨'], meaning: '悔' },
      { char: '迟', pinyin: 'chí', level: 'basic', words: ['迟到', '推迟'], meaning: '迟' },
      { char: '尔', pinyin: 'ěr', level: 'intermediate', words: ['尔等', '偶尔'], meaning: '你们' },
      { char: '小', pinyin: 'xiǎo', level: 'basic', words: ['小学', '小孩'], meaning: '小' },
      { char: '生', pinyin: 'shēng', level: 'basic', words: ['生活', '生命'], meaning: '生' },
      { char: '宜', pinyin: 'yí', level: 'basic', words: ['适宜', '应该'], meaning: '应该' },
      { char: '早', pinyin: 'zǎo', level: 'basic', words: ['早上', '早点'], meaning: '早' },
      { char: '思', pinyin: 'sī', level: 'basic', words: ['思考', '思想'], meaning: '思' },
    ]
  },
  // 第四十五段：梁灏
  {
    id: 'section-45',
    title: '若梁灏',
    content: '若梁灏，八十二。对大廷，魁多士。',
    pinyin: 'ruò liáng hào, bā shí èr. duì dà tíng, kuí duō shì.',
    difficulty: 'intermediate',
    characters: [
      { char: '若', pinyin: 'ruò', level: 'basic', words: ['如果', '如若'], meaning: '像' },
      { char: '梁', pinyin: 'liáng', level: 'basic', words: ['桥梁', '房梁'], meaning: '梁' },
      { char: '灏', pinyin: 'hào', level: 'advanced', words: ['灏然'], meaning: '梁灏' },
      { char: '八', pinyin: 'bā', level: 'basic', words: ['八个', '第八'], meaning: '八' },
      { char: '十', pinyin: 'shí', level: 'basic', words: ['十个', '第十'], meaning: '十' },
      { char: '二', pinyin: 'èr', level: 'basic', words: ['两个', '第二'], meaning: '二' },
      { char: '对', pinyin: 'duì', level: 'basic', words: ['对面', '回答'], meaning: '对' },
      { char: '大', pinyin: 'dà', level: 'basic', words: ['大大', '巨大'], meaning: '大' },
      { char: '廷', pinyin: 'tíng', level: 'intermediate', words: ['朝廷'], meaning: '朝廷' },
      { char: '魁', pinyin: 'kuí', level: 'advanced', words: ['魁首', '夺魁'], meaning: '夺魁' },
      { char: '多', pinyin: 'duō', level: 'basic', words: ['很多', '多数'], meaning: '多' },
      { char: '士', pinyin: 'shì', level: 'basic', words: ['士兵', '士人'], meaning: '士人' },
    ]
  },
  // 第四十六段：莹八岁
  {
    id: 'section-46',
    title: '莹八岁',
    content: '莹八岁，能咏诗。泌七岁，能赋棋。',
    pinyin: 'yíng bā suì, néng yǒng shī. mì qī suì, néng fù qí.',
    difficulty: 'intermediate',
    characters: [
      { char: '莹', pinyin: 'yíng', level: 'intermediate', words: ['晶莹'], meaning: '祖莹' },
      { char: '八', pinyin: 'bā', level: 'basic', words: ['八个', '第八'], meaning: '八' },
      { char: '岁', pinyin: 'suì', level: 'basic', words: ['岁月', '岁数'], meaning: '岁' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能' },
      { char: '咏', pinyin: 'yǒng', level: 'intermediate', words: ['咏唱', '吟咏'], meaning: '咏' },
      { char: '诗', pinyin: 'shī', level: 'basic', words: ['诗歌', '诗句'], meaning: '诗' },
      { char: '泌', pinyin: 'mì', level: 'advanced', words: ['分泌'], meaning: '李泌' },
      { char: '七', pinyin: 'qī', level: 'basic', words: ['七个', '第七'], meaning: '七' },
      { char: '岁', pinyin: 'suì', level: 'basic', words: ['岁月', '岁数'], meaning: '岁' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能' },
      { char: '赋', pinyin: 'fù', level: 'intermediate', words: ['赋予', '天赋'], meaning: '赋' },
      { char: '棋', pinyin: 'qí', level: 'basic', words: ['棋子', '下棋'], meaning: '棋' },
    ]
  },
  // 第四十七段：蔡文姬
  {
    id: 'section-47',
    title: '蔡文姬',
    content: '蔡文姬，能辨琴。谢道韫，能咏吟。',
    pinyin: 'cài wén jī, néng biàn qín. xiè dào yùn, néng yǒng yín.',
    difficulty: 'advanced',
    characters: [
      { char: '蔡', pinyin: 'cài', level: 'basic', words: ['蔡国', '老蔡'], meaning: '蔡' },
      { char: '文', pinyin: 'wén', level: 'basic', words: ['文化', '文学'], meaning: '文' },
      { char: '姬', pinyin: 'jī', level: 'basic', words: ['姬妾', '美女'], meaning: '姬' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能' },
      { char: '辨', pinyin: 'biàn', level: 'basic', words: ['分辨', '辨别'], meaning: '辨别' },
      { char: '琴', pinyin: 'qín', level: 'basic', words: ['琴声', '钢琴'], meaning: '琴' },
      { char: '谢', pinyin: 'xiè', level: 'basic', words: ['感谢', '谢谢'], meaning: '谢' },
      { char: '道', pinyin: 'dào', level: 'basic', words: ['道理', '道路'], meaning: '道' },
      { char: '韫', pinyin: 'yùn', level: 'advanced', words: ['蕴藏'], meaning: '韫' },
      { char: '能', pinyin: 'néng', level: 'basic', words: ['能够', '能力'], meaning: '能' },
      { char: '咏', pinyin: 'yǒng', level: 'intermediate', words: ['咏唱', '吟咏'], meaning: '咏' },
      { char: '吟', pinyin: 'yín', level: 'basic', words: ['吟诵', '呻吟'], meaning: '吟' },
    ]
  },
  // 第四十八段：刘晏
  {
    id: 'section-48',
    title: '刘晏贤',
    content: '刘晏贤，方七岁。举神童，正字字。',
    pinyin: 'liú yàn xián, fāng qī suì. jǔ shén tóng, zhèng zì zì.',
    difficulty: 'intermediate',
    characters: [
      { char: '刘', pinyin: 'liú', level: 'basic', words: ['刘国', '老刘'], meaning: '刘' },
      { char: '晏', pinyin: 'yàn', level: 'intermediate', words: ['晏子'], meaning: '晏' },
      { char: '贤', pinyin: 'xián', level: 'basic', words: ['贤惠', '圣贤'], meaning: '贤' },
      { char: '方', pinyin: 'fāng', level: 'basic', words: ['方正', '方才'], meaning: '方' },
      { char: '七', pinyin: 'qī', level: 'basic', words: ['七个', '第七'], meaning: '七' },
      { char: '岁', pinyin: 'suì', level: 'basic', words: ['岁月', '岁数'], meaning: '岁' },
      { char: '举', pinyin: 'jǔ', level: 'basic', words: ['举起', '举荐'], meaning: '举' },
      { char: '神', pinyin: 'shén', level: 'basic', words: ['神仙', '神话'], meaning: '神' },
      { char: '童', pinyin: 'tóng', level: 'basic', words: ['儿童', '童话'], meaning: '童' },
      { char: '正', pinyin: 'zhèng', level: 'basic', words: ['正确', '正式'], meaning: '正' },
      { char: '字', pinyin: 'zì', level: 'basic', words: ['文字', '字体'], meaning: '字' },
    ]
  },
  // 第四十九段：勤学
  {
    id: 'section-49',
    title: '彼颖悟',
    content: '彼颖悟，人称奇。尔幼学，当效之。',
    pinyin: 'bǐ yǐng wù, rén chēng qí. ěr yòu xué, dāng xiào zhī.',
    difficulty: 'intermediate',
    characters: [
      { char: '彼', pinyin: 'bǐ', level: 'intermediate', words: ['彼此', '彼岸'], meaning: '他' },
      { char: '颖', pinyin: 'yǐng', level: 'intermediate', words: ['聪颖', '新颖'], meaning: '聪颖' },
      { char: '悟', pinyin: 'wù', level: 'intermediate', words: ['领悟', '觉悟'], meaning: '悟' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '称', pinyin: 'chēng', level: 'basic', words: ['称呼', '称赞'], meaning: '称' },
      { char: '奇', pinyin: 'qí', level: 'basic', words: ['奇怪', '奇迹'], meaning: '奇' },
      { char: '尔', pinyin: 'ěr', level: 'intermediate', words: ['尔等', '偶尔'], meaning: '你们' },
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '幼' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '当', pinyin: 'dāng', level: 'basic', words: ['应当', '当时'], meaning: '应当' },
      { char: '效', pinyin: 'xiào', level: 'basic', words: ['效果', '效仿'], meaning: '效仿' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '他们' },
    ]
  },
  // 第五十段：犬守夜
  {
    id: 'section-50',
    title: '犬守夜',
    content: '犬守夜，鸡司晨。苟不学，曷为人。',
    pinyin: 'quǎn shǒu yè, jī sī chén. gǒu bù xué, hé wéi rén.',
    difficulty: 'basic',
    characters: [
      { char: '犬', pinyin: 'quǎn', level: 'basic', words: ['猎犬', '犬类'], meaning: '狗' },
      { char: '守', pinyin: 'shǒu', level: 'basic', words: ['守护', '防守'], meaning: '守' },
      { char: '夜', pinyin: 'yè', level: 'basic', words: ['黑夜', '夜晚'], meaning: '夜' },
      { char: '鸡', pinyin: 'jī', level: 'basic', words: ['鸡鸭', '鸡蛋'], meaning: '鸡' },
      { char: '司', pinyin: 'sī', level: 'basic', words: ['公司', '司仪'], meaning: '管' },
      { char: '晨', pinyin: 'chén', level: 'basic', words: ['早晨', '清晨'], meaning: '早晨' },
      { char: '苟', pinyin: 'gǒu', level: 'intermediate', words: ['苟且'], meaning: '如果' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '曷', pinyin: 'hé', level: 'advanced', words: ['曷不'], meaning: '怎么' },
      { char: '为', pinyin: 'wéi', level: 'basic', words: ['作为', '行为'], meaning: '做' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
    ]
  },
  // 第五十一段：蚕吐丝
  {
    id: 'section-51',
    title: '蚕吐丝',
    content: '蚕吐丝，蜂酿蜜。人不学，不如物。',
    pinyin: 'cán tǔ sī, fēng niàng mì. rén bù xué, bù rú wù.',
    difficulty: 'basic',
    characters: [
      { char: '蚕', pinyin: 'cán', level: 'basic', words: ['蚕豆', '蚕茧'], meaning: '蚕' },
      { char: '吐', pinyin: 'tǔ', level: 'basic', words: ['吐痰', '吞吐'], meaning: '吐' },
      { char: '丝', pinyin: 'sī', level: 'basic', words: ['丝绸', '丝线'], meaning: '丝' },
      { char: '蜂', pinyin: 'fēng', level: 'basic', words: ['蜜蜂', '蜂蜜'], meaning: '蜜蜂' },
      { char: '酿', pinyin: 'niàng', level: 'intermediate', words: ['酿造', '酝酿'], meaning: '酿' },
      { char: '蜜', pinyin: 'mì', level: 'basic', words: ['甜蜜', '蜜糖'], meaning: '蜜' },
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '学', pinyin: 'xué', level: 'basic', words: ['学习', '学校'], meaning: '学' },
      { char: '不', pinyin: 'bù', level: 'basic', words: ['不能', '不要'], meaning: '不' },
      { char: '如', pinyin: 'rú', level: 'basic', words: ['如果', '如'], meaning: '如' },
      { char: '物', pinyin: 'wù', level: 'basic', words: ['物体', '动物'], meaning: '物' },
    ]
  },
  // 第五十二段：习业
  {
    id: 'section-52',
    title: '幼习业',
    content: '幼习业，壮致身。上匡国，下利民。',
    pinyin: 'yòu xí yè, zhuàng zhì shēn. shàng kuāng guó, xià lì mín.',
    difficulty: 'intermediate',
    characters: [
      { char: '幼', pinyin: 'yòu', level: 'basic', words: ['幼小', '幼儿'], meaning: '幼' },
      { char: '习', pinyin: 'xí', level: 'basic', words: ['学习', '习惯'], meaning: '习' },
      { char: '业', pinyin: 'yè', level: 'basic', words: ['事业', '职业'], meaning: '业' },
      { char: '壮', pinyin: 'zhuàng', level: 'basic', words: ['强壮', '壮年'], meaning: '壮' },
      { char: '致', pinyin: 'zhì', level: 'intermediate', words: ['导致', '致使'], meaning: '致' },
      { char: '身', pinyin: 'shēn', level: 'basic', words: ['身体', '自身'], meaning: '身' },
      { char: '上', pinyin: 'shàng', level: 'basic', words: ['上面', '向上'], meaning: '上' },
      { char: '匡', pinyin: 'kuāng', level: 'intermediate', words: ['匡扶', '匡正'], meaning: '匡扶' },
      { char: '国', pinyin: 'guó', level: 'basic', words: ['国家', '祖国'], meaning: '国' },
      { char: '下', pinyin: 'xià', level: 'basic', words: ['下面', '向下'], meaning: '下' },
      { char: '利', pinyin: 'lì', level: 'basic', words: ['利益', '有利'], meaning: '利' },
      { char: '民', pinyin: 'mín', level: 'basic', words: ['人民', '公民'], meaning: '民' },
    ]
  },
  // 第五十三段：显名
  {
    id: 'section-53',
    title: '扬名声',
    content: '扬名声，显父母。光于前，裕于后。',
    pinyin: 'yáng míng shēng, xiǎn fù mǔ. guāng yú qián, yù yú hòu.',
    difficulty: 'basic',
    characters: [
      { char: '扬', pinyin: 'yáng', level: 'basic', words: ['宣扬', '发扬'], meaning: '扬' },
      { char: '名', pinyin: 'míng', level: 'basic', words: ['名声', '名字'], meaning: '名' },
      { char: '声', pinyin: 'shēng', level: 'basic', words: ['声音', '声望'], meaning: '声' },
      { char: '显', pinyin: 'xiǎn', level: 'basic', words: ['显示', '明显'], meaning: '显' },
      { char: '父', pinyin: 'fù', level: 'basic', words: ['父亲', '父母'], meaning: '父' },
      { char: '母', pinyin: 'mǔ', level: 'basic', words: ['母亲', '父母'], meaning: '母' },
      { char: '光', pinyin: 'guāng', level: 'basic', words: ['光芒', '光明'], meaning: '光' },
      { char: '于', pinyin: 'yú', level: 'basic', words: ['关于', '由于'], meaning: '于' },
      { char: '前', pinyin: 'qián', level: 'basic', words: ['前面', '前进'], meaning: '前' },
      { char: '裕', pinyin: 'yù', level: 'intermediate', words: ['富裕', '充裕'], meaning: '裕' },
      { char: '于', pinyin: 'yú', level: 'basic', words: ['关于', '由于'], meaning: '于' },
      { char: '后', pinyin: 'hòu', level: 'basic', words: ['后面', '后来'], meaning: '后' },
    ]
  },
  // 第五十四段：勤学
  {
    id: 'section-54',
    title: '人遗子',
    content: '人遗子，金满籯。我教子，唯一经。',
    pinyin: 'rén yí zǐ, jīn mǎn yíng. wǒ jiào zǐ, wéi yī jīng.',
    difficulty: 'basic',
    characters: [
      { char: '人', pinyin: 'rén', level: 'basic', words: ['人民', '人们'], meaning: '人' },
      { char: '遗', pinyin: 'yí', level: 'intermediate', words: ['遗产', '遗留'], meaning: '遗' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '金', pinyin: 'jīn', level: 'basic', words: ['黄金', '金子'], meaning: '金' },
      { char: '满', pinyin: 'mǎn', level: 'basic', words: ['满意', '充满'], meaning: '满' },
      { char: '籯', pinyin: 'yíng', level: 'advanced', words: ['筐籯'], meaning: '筐' },
      { char: '我', pinyin: 'wǒ', level: 'basic', words: ['我们', '自己'], meaning: '我' },
      { char: '教', pinyin: 'jiào', level: 'basic', words: ['教导', '教育'], meaning: '教' },
      { char: '子', pinyin: 'zǐ', level: 'basic', words: ['子女', '儿子'], meaning: '子' },
      { char: '唯', pinyin: 'wéi', level: 'basic', words: ['唯一', '唯独'], meaning: '唯' },
      { char: '一', pinyin: 'yī', level: 'basic', words: ['一个', '第一'], meaning: '一' },
      { char: '经', pinyin: 'jīng', level: 'basic', words: ['经书', '经典'], meaning: '经' },
    ]
  },
  // 第五十五段：结束语
  {
    id: 'section-55',
    title: '勤有功',
    content: '勤有功，戏无益。戒之哉，宜勉力。',
    pinyin: 'qín yǒu gōng, xì wú yì. jiè zhī zāi, yí miǎn lì.',
    difficulty: 'basic',
    characters: [
      { char: '勤', pinyin: 'qín', level: 'basic', words: ['勤劳', '勤奋'], meaning: '勤' },
      { char: '有', pinyin: 'yǒu', level: 'basic', words: ['拥有', '没有'], meaning: '有' },
      { char: '功', pinyin: 'gōng', level: 'basic', words: ['功夫', '成功'], meaning: '功' },
      { char: '戏', pinyin: 'xì', level: 'basic', words: ['游戏', '戏曲'], meaning: '戏' },
      { char: '无', pinyin: 'wú', level: 'basic', words: ['无', '没有'], meaning: '无' },
      { char: '益', pinyin: 'yì', level: 'basic', words: ['利益', '有益'], meaning: '益' },
      { char: '戒', pinyin: 'jiè', level: 'basic', words: ['警告', '戒备'], meaning: '戒' },
      { char: '之', pinyin: 'zhī', level: 'basic', words: ['之前', '之后'], meaning: '之' },
      { char: '哉', pinyin: 'zāi', level: 'intermediate', words: ['呜呼哀哉'], meaning: '哉' },
      { char: '宜', pinyin: 'yí', level: 'basic', words: ['适宜', '应该'], meaning: '宜' },
      { char: '勉', pinyin: 'miǎn', level: 'intermediate', words: ['勉励', '勤勉'], meaning: '勉' },
      { char: '力', pinyin: 'lì', level: 'basic', words: ['力量', '努力'], meaning: '力' },
    ]
  },
];

export function getAllSanziJingCharacters() {
  return sanziJingSections.flatMap(section => section.characters);
}
